### ISSUE TITLE
Typo On Readme page

### ISSUE THREAD

**Issue by just1nw** [wallabag/docker#101]
Hello, I just wanted to report that there is a typo on the readme.md page. In the [SQLite section](https://github.com/wallabag/docker/blob/master/README.md#sqlite) there's an extra apostrophe in the 2nd command in front of /opt which causes the command to fail.

![Readme Typo](https://user-images.githubusercontent.com/8879370/35179092-1e197954-fd50-11e7-944b-5b44ac8b6fe3.jpg)

**Comment by TomFaulkner** [comment]
Submitted a PR for this.
