### ISSUE TITLE
Website thinks my server is from Europe

### ISSUE THREAD

**Issue by jpbaril** [wallabag/docker#117]
Bonjour / Hi from Québec (Canada),

I just installed wallabag on my server (in Canada) using official docker image and imported my articles from Pocket.

One of the articles is from a Canadian site that does geolocalisation and blocks Wallabag because it thinks my server is from Europe.

I suppose it is because the container is configured with a European timezone (or just not timezone at all so probably Greenwich).

Would there be any variable that could be set in Docker-compose file to make it works?

I'm aware this is a very specific and unusual issue.

Thanks.

**Comment by SkysCrystal** [comment]
Hi! Can you give a hint about how to set the timezone in `docker-compose.yml`? Thanks!

**Comment by j0k3r** [comment]
Manual edit https://github.com/wallabag/docker/blob/5c52eee713212900507a831dfbe30a54e080b48c/root/etc/php81/php.ini#L879 ?

**Comment by SkysCrystal** [comment]
> Manual edit
> 
> https://github.com/wallabag/docker/blob/5c52eee713212900507a831dfbe30a54e080b48c/root/etc/php81/php.ini#L879
> 
> ?

Thank you for your reply!
Edit it in the Docker? In this way, I will need to change this every time when I upgrade the Wallabag Docker image, which is inconvenient. 
I just can't change this in `docker-compose.yml` like:
```
environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://mydomain.com/
      - SYMFONY__ENV__SERVER_NAME="Wallabag"
      - TZ=Asia/Shanghai
```
This doesn't work.
