### ISSUE TITLE
permission problems

### ISSUE THREAD

**Issue by g33kdad** [wallabag/docker#120]
Hello,

I am trying to deploy the container with sqlite backend on centos7 and i keep getting errors that "provisioner" cant create directories (errno 13). i know nothing about ansible so i just have no idea where to go with this... i assume that i am using the '-v' wrong somehow or that my data directory has bad permissions, but i tried changing it to '777' and it still wont run.

please let me know if i haven't provided enough information

sorry so newb

Thanks,
matt

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
