### ISSUE TITLE
following documented setup documentation does not result in working instance, db not initialized

### ISSUE THREAD

**Issue by norweeg** [wallabag/docker#138]
Following the instructions Readme.md does not result in a working instance.  Instead, I get http 500 error with the following on the container log:

[error] 256#256: *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_craue_config_setting' doesn't exist in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105

Nowhere is it documented how to initialize the db and the POPULATE_DATABASE environment variable seemingly does nothing

**Comment by norweeg** [comment]
Using with a mariadb container, using with environment variables set according to examples in Readme.md

**Comment by benoitberenger** [comment]
I got the same issue and followed this : https://github.com/wallabag/wallabag/issues/1971#issuecomment-213818746

**Comment by norweeg** [comment]
closing this.  apparently you must absolutely NOT start your db container with an env variable such as MYSQL_DATABASE set.  The wallabag container apparently expects to be able to create this database itself and will fail if the database already exists, and you don't have any say over the name of the database.  This is very unlike every other container using a database I have ever deployed before, which expect YOU to tell them what database to use and YOU have to initialize that table by setting MYSQL_DATABASE in your db container.
