### ISSUE TITLE
Blank page + PHP Fatal error

### ISSUE THREAD

**Issue by menteb** [wallabag/docker#152]
I see the following in my logs after the install and being presented with a white page:

`2019/03/12 17:22:13 [error] 241#241: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Asset\Exception\InvalidArgumentException: "subdomain.example.com" is not a valid URL in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Asset/UrlPackage.php:133`

Any ideas? Do I need to chown /var/www/wallabag to nginx?

**Comment by menteb** [comment]
Never mind. had to add https:// to docker-compose.yml for the domain

**Comment by xcffl** [comment]
> Never mind. had to add https:// to docker-compose.yml for the domain

Maybe we should indicate that in the doc

**Comment by fivestones** [comment]
On the dockerhub.com wallabag page it actually lists in the example docker-compose.yml the wrong setting (without the https://). This caused me a lot of trouble.

`    - SYMFONY__ENV__DOMAIN_NAME=your-wallabag-url-instance.com`

Can this be changed? As below:

`    - SYMFONY__ENV__DOMAIN_NAME=https://your-wallabag-url-instance.com`

**Comment by j0k3r** [comment]
@fivestones I've updated the readme

**Comment by fivestones** [comment]
Sweet. Thanks!
