### ISSUE TITLE
Multiarch images

### ISSUE THREAD

**Issue by cinemast** [wallabag/docker#157]
Hi!

Thank you for providing wallabag. Could you please provide the docker image also for `arm` and `arm64`?

**Comment by leolivier** [comment]
Hi
Actually I tried building wallabag image for amr32v7 (on a RaspberryPi 4) using the standard Dockerfile provided on this site and it fails because of the following missing packages in alpine:
* py-mysqldb
* py-psycopg2

Full trace of failing step:
```
Step 4/9 : RUN set -ex  && apk update  && apk upgrade --available  && apk add     ansible       curl       git       libwebp       mariadb-client       nginx       pcre       php7       php7-amqp       php7-bcmath       php7-ctype       php7-curl       php7-dom       php7-fpm       php7-gd       php7-gettext       php7-iconv       php7-json       php7-mbstring       php7-openssl       php7-pdo_mysql       php7-pdo_pgsql       php7-pdo_sqlite       php7-phar       php7-session       php7-simplexml       php7-tokenizer       php7-xml       php7-zlib       php7-sockets       php7-xmlreader       php7-tidy       py-mysqldb       py-psycopg2       py-simplejson       rabbitmq-c       s6       tar       tzdata  && rm -rf /var/cache/apk/*  && ln -sf /dev/stdout /var/log/nginx/access.log  && ln -sf /dev/stderr /var/log/nginx/error.log  && curl -s https://getcomposer.org/installer | php  && mv composer.phar /usr/local/bin/composer  && git clone --branch $WALLABAG_VERSION --depth 1 https://github.com/wallabag/wallabag.git /var/www/wallabag
 ---> Running in 6c254dc24ec1
+ apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
v3.11.6-41-ga073b3140f [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.6-40-g4ab6ec338e [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 10937 distinct packages available
+ apk upgrade --available
OK: 4 MiB in 14 packages
+ apk add ansible curl git libwebp mariadb-client nginx pcre php7 php7-amqp php7-bcmath php7-ctype php7-curl php7-dom php7-fpm php7-gd php7-gettext php7-iconv php7-json php7-mbstring php7-openssl php7-pdo_mysql php7-pdo_pgsql php7-pdo_sqlite php7-phar php7-session php7-simplexml php7-tokenizer php7-xml php7-zlib php7-sockets php7-xmlreader php7-tidy py-mysqldb py-psycopg2 py-simplejson rabbitmq-c s6 tar tzdata
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/armv7/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  py-mysqldb (missing):
    required by: world[py-mysqldb]
  py-psycopg2 (missing):
    required by: world[py-psycopg2]
The command '/bin/sh -c set -ex  && apk update  && apk upgrade --available  && apk add        ansible       curl       git       libwebp       mariadb-client       nginx       pcre       php7       php7-amqp       php7-bcmath       php7-ctype       php7-curl       php7-dom       php7-fpm       php7-gd       php7-gettext       php7-iconv       php7-json       php7-mbstring       php7-openssl       php7-pdo_mysql       php7-pdo_pgsql       php7-pdo_sqlite       php7-phar       php7-session       php7-simplexml       php7-tokenizer       php7-xml       php7-zlib       php7-sockets       php7-xmlreader       php7-tidy       py-mysqldb       py-psycopg2       py-simplejson       rabbitmq-c       s6       tar       tzdata  && rm -rf /var/cache/apk/*  && ln -sf /dev/stdout /var/log/nginx/access.log  && ln -sf /dev/stderr /var/log/nginx/error.log  && curl -s https://getcomposer.org/installer | php  && mv composer.phar /usr/local/bin/composer  && git clone --branch $WALLABAG_VERSION --depth 1 https://github.com/wallabag/wallabag.git /var/www/wallabag' returned a non-zero code: 2

```

**Comment by leolivier** [comment]
Actually, I found why it fails: these 2 packages are not in alpine 3.11 for an unknown reason!
See the difference between
* https://pkgs.alpinelinux.org/packages?name=py-psycopg2&branch=v3.10&arch=armv7 
and 
* https://pkgs.alpinelinux.org/packages?name=py-psycopg2&branch=v3.11&arch=armv7

for instance... So I changed 
`FROM alpine:latest
`
in 
`FROM alpine:3.10`
And now it's building...
@cinemast, it's probably too late for you but if it works I'll upload it to docker hub...
Let me know if you're still interested.

**Comment by fdw** [comment]
It doesn't seem that the fix has ever been merged, has it? Is there a reason why there are no official armv7/arm64 docker images?

**Comment by j0k3r** [comment]
What fix should have been merged? I don't see any PR attached to that issue.
Also, there is an issue about arm 7 in the main repo: https://github.com/wallabag/wallabag/issues/4872

If there is no support for _put whatever software or version update_ is often mainly because we do not have time to add it.

**Comment by fdw** [comment]
Thank you; I hadn't seen the other issue in the main repo.

**Comment by Michaelpalacce** [comment]
Making an ARM image isn't so hard. I did it using docker buildx. If you are interested, you can checkout:

https://github.com/Michaelpalacce/Docker/blob/master/wallabag/BUILD.sh

After you have initialized a docker buildx builder.

If you want the end result:

https://hub.docker.com/repository/docker/stefangenov/wallabag

I don't claim ownership of anything, but I did need an arm build 😄.

If I miss a version, submit me an issue and I can run a build.

If the developer wants to officially support arm builds I will remove mine.

**Comment by leolivier** [comment]
@Michaelpalacce great!
I think it can be interesting for a lot of people if I look at the 10k+ downloads of my own [armv7 docker image](https://hub.docker.com/repository/docker/leolivier/wallabag)  
I would suggest:
* adding linux/armv7 in the platform list
* doing a PR for that to replace the current way wallabag docker is built...

**Comment by Kdecherf** [comment]
We now officially provide arm64/armv7 images
