### ISSUE TITLE
Bad gatewway when adding some specific articles

### ISSUE THREAD

**Issue by m0wer** [wallabag/docker#167]
When adding some specific websites, I get a 502 error. In this case with <https://blog.lukaszolejnik.com/stealing-sensitive-browser-data-with-the-w3c-ambient-light-sensor-api/> using **wallabag/wallabag:2.3.8**.

In the php-fpm logs i see a SIGSEV. The graby parser is working fine apparently. The database logs don't show any errors. The database is `mariadb:10.3 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci`. Before, when the detched site had special characters such as emojis, the database failed, which was fixed by setting the **utf8mb4** encoding.

**Comment by j0k3r** [comment]
We'll need more log to be able to diagnose the issue.

**Comment by m0wer** [comment]
> We'll need more log to be able to diagnose the issue.

Can you replicate the error?

**Comment by m0wer** [comment]
From `docker logs wallabag`:

```
172.19.0.1 - - [20/Oct/2019:17:06:38 +0000] "POST /new-entry HTTP/1.1" 502 568 "https://[undisclosed]/" "Mozilla/5.0 (X11; Linux x86_64) [undisclosed]"
2019/10/20 17:06:38 [error] 232#232: *269 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: _, request: "POST /new-entry HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "[undisclosed]", referrer: "https://[undisclosed]/"
```

Nothing relevant in * /var/www/wallabag/var/logs/prod.log* inside the docker.

In */var/log/php-fpm.log*:

```
[20-Oct-2019 17:06:38] WARNING: [pool www] child 233 exited on signal 11 (SIGSEGV) after 124582.207429 seconds from start
[20-Oct-2019 17:06:39] NOTICE: [pool www] child 254 started
```

Let me know if you need anything else :-)

**Comment by Whisprin** [comment]
I'm encountering this bug as well: using the link provided in the first comment as well as this one: https://kenkantzer.com/learnings-from-5-years-of-tech-startup-code-audits/
My logs look pretty much the same

@m0wer did you find a solution or workaround?

**Comment by m0wer** [comment]
@Whisprin I no longer have this issue. I could add the link I mentioned and yours withour trouble. Using `wallabag/wallabag:latest`.
