### ISSUE TITLE
How to change password for wallabag user?

### ISSUE THREAD

**Issue by diggnsaegg** [wallabag/docker#179]
Hey,

I successfully run wallabag with podman, to secure things I want to change the password for the wallabag user or just delete it. I didn't find an option to simply change the password besides the email reset option, I do not have any mailserver at my home and I do not want one. I saw I could delete the wallabag user but didn't find an option to give admin permissions to another user.

Any help here?

Thanks

Dan

**Comment by diggnsaegg** [comment]
I read the documentation, so it is possible to change passwords and role via CLI.
anyways, a "podman exec -it wallabag /bin/sh" and executing "console" throws me this error:

`/var/www/wallabag/bin # console
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:49
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(29): Symfony\Component\Console in /var/www/wallabag/app/AppKernel.php on line 49
`

**Comment by j0k3r** [comment]
You forgot to define the environment when running the CLI command. Add `--env=prod` and it'll be fine

**Comment by diggnsaegg** [comment]
Got it, thanks!

**Comment by PabloCastellano** [comment]
For documentation sake, here is the command to change a user password:

```
# locate your $CONTAINER_ID first
docker exec -ti $CONTAINER_ID /var/www/wallabag/bin/console --env=prod fos:user:change-password
```

**Comment by subzero355** [comment]
I enabled 2FA and I'm not getting any email for the auth code, any way to disable 2FA?
