### ISSUE TITLE
Release new image for wallabag 2.1.1

### ISSUE THREAD

**Issue by nicosomb** [wallabag/docker#19]
I don't know if we just need to update the milestone in the dockerfile, because we have Redis and RabbitMQ in this new release.

**Comment by xsteadfastx** [comment]
Is redis a dependency? We could add it to the image itself or update the docs that a redis container is needed.

**Comment by tcitworld** [comment]
It's not a dependency but it's really recommended.

**Comment by xsteadfastx** [comment]
So we can decide if we want to add it to the container

**Comment by nicosomb** [comment]
2.1.1 will be available in few hours

**Comment by bobberb** [comment]
"RabbitMQ was created specifically for queueing, whereas Redis is an in-memory datastore"

Any reason, @xsteadfastx , for a preference for redis for wallabag's docker?

**Comment by nicosomb** [comment]
@bobberb it's lighter to install and to maintain than RabbitMQ.

**Comment by nsteinmetz** [comment]
Hi,

Redis/RabbitMQ are just required for import purpose, right ? For a "normal usage", it's not required. I don't expect to increase in complexity for an optional requirement I may not need.

So +1 to make it optionnal in the compose file.

**Comment by xsteadfastx** [comment]
I'm in vacation right now and tomorrow at my computer. I will give redis a try to add it directly to the image. Any parameters I have to set?

**Comment by xsteadfastx** [comment]
Or we really add it only to the docs. If it's just needed for import.

**Comment by bobberb** [comment]
if you are not wed to having redis in the image itself you can --link redis:redis the official image.

**Comment by j0k3r** [comment]
Agree with @nsteinmetz optional is better.

**Comment by xsteadfastx** [comment]
OK. So we will just change the docs.

**Comment by xsteadfastx** [comment]
im still fighting with the new parameters.yml. i guess i need to check if the environment variable redis is there... that i have to add that to the parameters.yml file. and if we do it that way.... i need so create a parameters.yml template and fill it up with ansible.

**Comment by xsteadfastx** [comment]
and there is no php-amqplib for alpine yet.

**Comment by xsteadfastx** [comment]
i dont get it running. it dont want to use my environment variables "env.secret" and "env.mailer_host" no more. i always get a 

```

```2016/10/05 10:33:26 [error] 197#197: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "env.mailer_host". Did you mean this: "mailer_host"? in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84
wallabag_1  | Stack trace:
wallabag_1  | #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('env.mailer_host')
wallabag_1  | #1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(171): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%env.mailer_hos...', Array)
wallabag_1  | #2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%env.mailer_hos...', Array)
wallabag_1  | #3 /va" while reading response header from upstream, client: ::ffff:172.19.0.6, server: _, request: "GET / HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag"

**Comment by Thrilleratplay** [comment]
@xsteadfastx If leaving `env.secret` and `env.mailer_host` as is for right now, are you able to create a docker image for 2.1.1?  

Removing environmental parameters could be spun off into another issue and labeled as an enhancement.

**Comment by xsteadfastx** [comment]
All env variables get ignored in the parameters file right now. I could solve this by writing a ansible template for it. 

Another issue is the db changes. It has to be a drop in replacement. Get the latest  image and everything will be handled. All db upgrades and stuff. 

Am 8. Oktober 2016 17:20:07 MESZ, schrieb Tom Hiller <notifications@github.com>:

**Comment by bobberb** [comment]
Db changes? Is pointing at the old .sqlite a non-option for upgrading?

**Comment by der-On** [comment]
Any chance of seeing this working soon? Do you need help?

**Comment by xsteadfastx** [comment]
i have set up a branch [here](https://github.com/wallabag/docker/tree/upgradeto2.1.1)
it looks like redis works now but database migration is still a problem. i cant run the the migrate command on every container start.

**Comment by nsteinmetz** [comment]
> it looks like redis works now but database migration is still a problem. i cant run the the migrate command on every container start.

I was to say, why not create file once migraiton is run but it won't work once you re-create a container. What about a dummy table in the SQL backend which stores for exemple the value for the wallabag version ?

Once migration command is run ,value is updated to current version. Once started if current version is > version in DB, then apply migration. Otherwise do nothing ?

The DB seems the only place to keep a persistent info.

Hope it helps,
Nicolas

**Comment by xsteadfastx** [comment]
@nsteinmetz thats a nice idea. the best way in my opinion would be a web view for a db upgrade. for example with nextcloud... i have a new image for a new version... i run it and when i browse it, it tells me that there is a db migration needed and does it for me.

**Comment by nsteinmetz** [comment]
@xsteadfastx so it should be part of wallabag then and not related to the docker image.

Coud you release an image where, even if it's a best practice, we have to run manually the migration commands for people who have an existing installation of wallabag ? It's a little bit "stupid" to block the release for people without an existing instance only for a few ones, don"t you thnk ?

**Comment by xsteadfastx** [comment]
i created a PR #21
