### ISSUE TITLE
Add environment variable for twofactor_auth parameter

### ISSUE THREAD

**Issue by ywoly** [wallabag/docker#192]
### Issue details

Almost all parameters in `/var/www/wallabag/app/config/parameters.yml` can be modified by means of environment variables, as described in [README](https://github.com/wallabag/docker/blob/master/README.md), except `twofactor_auth` which is set to `true` by default.

It would be also useful to disable that parameter directly via an environment variable in Docker (`SYMFONY__ENV__TWOFACTOR_AUTH`) to prevent users from enabling 2FA in their Wallabag account, in particular if no mail server is defined since that actually makes the account blocked because the users will never receive any second factor by email.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? `docker pull wallabag/wallabag:latest`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

**Comment by j0k3r** [comment]
That’s a good idea.
Do you want to help us and provide a PR to fix that?
