### ISSUE TITLE
docker version of entries.xml.twig template not the same as in wallabag project

### ISSUE THREAD

**Issue by alx** [wallabag/docker#197]
Hi Wallabag team,

I've got an issue with a file not similar in the docker version of wallabag, and the one available on main src. The version available in docker is a simplified version of the one available in main repo. I'm not sure why it's different, there's propably a related issue I'm not aware of.

I'm using `wallabag/wallabag` image within my `docker-compose.yml`.

Current version of `entries.xml.twig` in Wallabag src: https://raw.githubusercontent.com/wallabag/wallabag/master/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig

Current version of the same file available inside docker container - `/var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig`: [entries.xml.twig.txt](https://github.com/wallabag/docker/files/4527628/entries.xml.twig.txt)

**Comment by j0k3r** [comment]
It's because the docker image is tagged as of the 2.3.8 release.
See https://raw.githubusercontent.com/wallabag/wallabag/2.3.8/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig

There is no tag for the master branch

**Comment by alx** [comment]
Hi @j0k3r and thanks for the explanation.

Would you know a docker image containing master branch ?

**Comment by j0k3r** [comment]
You might be able to build your own image and replace `WALLABAG_VERSION` by `master` in the `Dockerfile` it should work.
Otherwise I don't any image using wallabag master branch.
