### ISSUE TITLE
Docker Hub Account

### ISSUE THREAD

**Issue by xsteadfastx** [wallabag/docker#2]
I think we should get a official wallabag docker hub account. Then we could work with the automated builds. Who should register it?

**Comment by nicosomb** [comment]
I can do it. But does everyone (who work on this repo) need credentials?

**Comment by xsteadfastx** [comment]
On Mon, 18. Apr 00:49, Nicolas Lœuillet wrote:
> I can do it. But does everyone (who work on this repo) need credentials?

Nope. You can set this up as a automated build. That means when
something changes in the repo... a new image gets build. I dont think we
need much configuration there in the registry.

**Comment by nicosomb** [comment]
https://hub.docker.com/r/wallabag/docker/

**Comment by DmitrySandalov** [comment]
The previous link is 404, I suppose you meant
https://hub.docker.com/r/wallabag/wallabag/

**Comment by nicosomb** [comment]
Sorry, because @xsteadfastx asked me to rename it on Gitter and I forgot to edit it here ;-)
