### ISSUE TITLE
How to use the wallabag:export command

### ISSUE THREAD

**Issue by Nebucatnetzer** [wallabag/docker#213]
I would like to export all my articles from Wallabag but I'm not sure how I would do this with the Docker setup?
```
sudo docker-compose exec wallabag wallabag:export
```
Doesn't work for me.

**Comment by d7eeem** [comment]
also the GUI export option defaults to 502 error with all cpus and ram allocated to docker

**Comment by j0k3r** [comment]
It depends on how many entries you have.

**Comment by krlvo** [comment]
Hi, did you ever figure this out? Want to set up a cron job to automatically backup.

**Comment by Nebucatnetzer** [comment]
No I unfortunately never found a working solution. 
I still have the VM because I would like to get them out eventually but so far I had to “export” the articles manually.

**Comment by krlvo** [comment]
I have found a solution that works for me. I now run this command:

`sudo docker exec -t CONTAINER_NAME /var/www/wallabag/bin/console wallabag:export wallabag --env=prod > /EXPORT_LOCATION/"$(date +"%F").json"`

I also found a way to do it via the API (via HTTPie). However, that's _a lot_ more cumbersome than the above command.

**Comment by Nebucatnetzer** [comment]
Got it sort of working with your command.
However I had to point it to an internal folder to really get the file out. Otherwise the file was just empty.

```
sudo docker-compose exec wallabag /var/www/wallabag/bin/console wallabag:export USERNAME --env=prod /var/www/wallabag/web/assets/images/export.json
```

In addition I needed to increase the allowed memory for PHP.

Now I just need to figure out a way to get the data out of the json file but that isn't really part of this issue.

**Comment by Nebucatnetzer** [comment]
I've created a small Python script to convert the exported json to individual Markdown files.
It's not pretty but it works, maybe someone else has use for it:
https://git.2li.ch/Nebucatnetzer/wallabag_to_markdown
