### ISSUE TITLE
Change docker hub repo to be managed by travis

### ISSUE THREAD

**Issue by xsteadfastx** [wallabag/docker#22]
So... we have a version for 2.1.1 now... but docker hub has some strange behavior building it. it throws a error... i tested it with a fork from this repo and added it too to the docker hub... it builds just fine. i guess its a problem with the cache or something. i had this error once and a docker engine restart "fixed" this for me.

so here is my idea: i read alot through bug reports from the docker hub and there is a tendency that they wont work on the hub no more to push the docker cloud. we use travis already to test the building. this works well. we also could push this image directly to the hub. or even better: to other registries too (like https://quay.io). We would have a little better control of the building process. Right now its an auto build on the docker hub and it checks for pushes on the repository and starts to build. if it fails... we cant do anything. 

im experimenting right now with my own fork to see what needs to be done. the worst scenario would be... to delete the repo and readd it as a normal docker hub repo because there is no way right now migrate the repo type.

**Comment by nicosomb** [comment]
ping @wallabag/core

**Comment by nicosomb** [comment]
The error is: 

`Build failed: lchown /var/lib/docker/overlay/af30f1f9e5a8a174e067b71cf4ae520ce4ab3d4a508e64d37da37484f98e21a6/merged/entrypoint.sh: no such file or directory`

**Comment by nicosomb** [comment]
There is a post here about this problem https://forums.docker.com/t/automated-docker-build-fails/22831

**Comment by xsteadfastx** [comment]
the image got built now... but still. we would have a little more power about the image if we let it build from travis.

**Comment by xsteadfastx** [comment]
And what i found it: we dont need to delete the repo and recreate it. We can disable to auto build and push manually to the registry.

**Comment by nicosomb** [comment]
Clearly, I don't want to delete the repo. And if possible, I want to stay on Docker hub.

**Comment by xsteadfastx** [comment]
we dont need to delete it at all. just disable the auto build and push it from travis to docker hub. plus the possibilities to use other registries as fallback.
