### ISSUE TITLE
Restore Wallabag Database

### ISSUE THREAD

**Issue by typkrft** [wallabag/docker#234]
Completely my fault, but I had a watchtower instance go through and update wallabag and my database and for some reason it stopped loading completely it would just load to a white screen. I had thought I labeled them so watchertower would not update them, but I guess I didn't. I saw some php errors but was unable to figure anything out. I saved my database files from my mariadb instance, but I am wondering if there is a way to restore either the database or at lease the bookmarks from the idb /frm files.

Restore the data base I can get back to my original error if maybe it is easier to resolve this. 

```shell

Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(129): PDOStatement->execute(NULL)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(906): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.usern...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php(84): Doctrine\ORM\EntityRepository->findOneBy(Array)
#5 /var/ww" while reading response header from upstream, client: 192.168.90.254, server: _, request: "POST /oauth/v2/token HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "SECRET"


192.168.90.254 - - [20/Dec/2020:11:09:27 +0000] "POST /oauth/v2/token HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11.1; rv:85.0) Gecko/20100101 Firefox/85.0"


2020/12/20 11:09:31 [error] 279#279: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.googleAuthenticatorSecret' in 'field list' in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129
```

I've also tried recreating then adding the entry db files and moving the Users and entry db files into a new db to no avail.

<p><del>In my parameters.yml it says database_path: `'%kernel.root_dir%/../data/db/wallabag.sqlite'`. But there is no wallabag.sqlite file in that folder that I can find. I'm not sure if thats part of the issue. </del></p>

**Comment by adrinux** [comment]
This looks like the error from the 2.4.0 upgrade, see this issue comment: https://github.com/wallabag/docker/issues/232#issuecomment-747879893

You need to run the migrate command...I still have errors personally, just not this one anymore...

**Comment by typkrft** [comment]
I ended up just grepping all my links out of my database and nuking everything, pulling new images, recreating it, and importing the links. I'll go ahead and close this.
