### ISSUE TITLE
insecure wallabag user present in database

### ISSUE THREAD

**Issue by meonkeys** [wallabag/docker#245]
I just noticed a `wallabag` user in my database with a very easy-to-guess password. Is this expected? I don't know where it came from and I didn't find mention of it in the documentation. I'm running wallabag 2.4.1 with Docker.

Is there documentation I'm missing about this user? Should I delete this user and make my usual user an admin instead?

**Comment by j0k3r** [comment]
How did you run the installation command?

**Comment by meonkeys** [comment]
By exec'ing into the container. https://github.com/wallabag/docker/issues/170#issuecomment-708198324

**Comment by eric-pierce** [comment]
@meonkeys that's the default user - I logged into it using wallabag/wallabag and deleted it from the settings screen.

**Comment by meonkeys** [comment]
Dup of #208
