### ISSUE TITLE
Can't get it to work at all in docker

### ISSUE THREAD

**Issue by jpatje** [wallabag/docker#247]
No matter what I try from the documentation, there is just no way that I can get this to work at all.  I tried the most simple example from the documentation:  _docker run -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag_
It's quite slow to startup and then I get a very simple webpage with login. No formatting, no graphics at all. It's all in plain blue or black text with a white background. 
I'm running on a Ubuntu 20 VM with Docker 2.0 and docker-compose.
What can be wrong?

**Comment by j0k3r** [comment]
Resolved? How?

**Comment by jpatje** [comment]
By changing the SYMFONY__ENV__DOMAIN_NAME variable to http://yourmachinename.local :)
