### ISSUE TITLE
How can I deal with it?

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/docker#251]
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
ce_appendices/interpreter_discovery.html for more information.

It is successfully installed and run

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                            NAMES
3af6b872f349        wallabag/wallabag   "/entrypoint.sh wall…"   30 seconds ago      Up 29 seconds       80/tcp, 0.0.0.0:3333->3333/tcp   wallabag

But I still can't open it.

I use this command to install
docker run -d --name wallabag -p 3333:3333 wallabag/wallabag

**Comment by j0k3r** [comment]
Regarding the log, it's not an error just warning.

> But I still can't open it.

What do you mean?
Maybe you need to pass extra param to the image https://github.com/wallabag/docker#how-to-use-this-image

**Comment by starsareintherose** [comment]
I can't visit the web page but the containers are still running. I set the proxy and SSL.

**Comment by starsareintherose** [comment]
I can find that when I visit the domain, it auto redirect to domain/login, so I successfully install it but I can only see "HTTP ERROR 500" on the page.

**Comment by starsareintherose** [comment]
After installing, if I visit IP: port (HTTP), it reports HTTP error 500, and redirect to IP: port/login, but it doesn't redirect when I use HTTPS and reports ERR_SSL_PROTOCOL_ERROR. If I visit the domain (HTTPS), it redirects to the domain/login and reports HTTP error 500.

**Comment by starsareintherose** [comment]
My SSL settings for nginx is here
```
{
    listen 80;
	listen 443 ssl http2;
    server_name read.malacology.net;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/read.malacology.net;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/read.malacology.net/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/read.malacology.net/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;


    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    #清理缓存规则

    location ~ /purge(/.*) {
        proxy_cache_purge cache_one $host$1$is_args$args;
        #access_log  /www/wwwlogs/read.malacology.net_purge_cache.log;
    }
	#引用反向代理规则，注释后配置的反向代理将无效
	include /www/server/panel/vhost/nginx/proxy/read.malacology.net/*.conf;

	include enable-php-00.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/read.malacology.net.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    access_log  /www/wwwlogs/read.malacology.net.log;
    error_log  /www/wwwlogs/read.malacology.net.error.log;
}
```

**Comment by gotmax23** [comment]
If you are trying to install this in docker, you have to follow the instructions in the README [here](https://github.com/wallabag/docker#how-to-use-this-image) for docker. It seems like you did not setup nginx correctly, so that is why you can't access your instance. I would recommend you use the docker-compose method in the instructions to setup wallabag and then create an nginx container and setup a reverse proxy.

There is also a subscription service available at [wallabag.it](https://www.wallabag.it), if you prefer to go that route.

I hope this helps!

**Comment by starsareintherose** [comment]
Sorry, the fact is that it doesn't work on my CentOS7 but okay on Ubuntu, same configure.
