### ISSUE TITLE
Unable to upgrade docker image 

### ISSUE THREAD

**Issue by hkdd** [wallabag/docker#253]
Here's the docker logs.  I just docker pull the latest image and try to run it.  Reverting to the previous container image version doesn't resolve it.  Neither web or clients are working any more.  

Provisioner finished.
172.18.0.1 - - [11/Mar/2021:17:52:39 +0000] "GET / HTTP/1.1" 302 213 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"
2021/03/11 17:52:40 [error] 242#242: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(67): PDO->prepare('SELECT t0.value...', Array)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(903): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.value...')
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.value...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(73): Doctrine\ORM\EntityRepository->findOneBy(Array)
#5 /var/www/wallabag" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.jonfu.com"
172.18.0.1 - - [11/Mar/2021:17:52:40 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"
2021/03/11 17:52:46 [error] 242#242: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: t0.googleAuthenticatorSecret in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(67): PDO->prepare('SELECT t0.usern...', Array)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(903): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.usern...')
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.usern...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php(84): Doctrine\ORM\EntityRepository->findOneBy(Array" while reading response header from upstream, client: 172.18.0.1, server: _, request: "POST /oauth/v2/token HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.jonfu.com"
172.18.0.1 - - [11/Mar/2021:17:52:46 +0000] "POST /oauth/v2/token HTTP/1.1" 500 31 "-" "wallabag/303 CFNetwork/1220.1 Darwin/20.3.0"
2021/03/11 17:52:51 [error] 242#242: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: t0.googleAuthenticatorSecret in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(67): PDO->prepare('SELECT t0.usern...', Array)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(903): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.usern...')
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.usern...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php(84): Doctrine\ORM\EntityRepository->findOneBy(Array" while reading response header from upstream, client: 172.18.0.1, server: _, request: "POST /oauth/v2/token HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.jonfu.com"
172.18.0.1 - - [11/Mar/2021:17:52:51 +0000] "POST /oauth/v2/token HTTP/1.1" 500 31 "-" "wallabag/303 CFNetwork/1220.1 Darwin/20.3.0"

**Comment by hkdd** [comment]
Actually, reverting to 2.3.8 does at least continue to work, but it seems like anything >=2.4.0 throws this error.

**Comment by j0k3r** [comment]
See https://github.com/wallabag/docker#upgrading

**Comment by hkdd** [comment]
Thanks, that did the trick.
