### ISSUE TITLE
Error on TASK [run composer] using SQLite

### ISSUE THREAD

**Issue by ChristianAE** [wallabag/docker#26]
When using the command `docker run -p 9990:80 wallabag/wallabag` to spin up wallabag using SQLite I get the attached error.
I'm using Docker version 1.11.2, build b9f10c9 on an Ubuntu 14.04.

Using mariaDB in a separate container as suggested in the documentation works. 

I'm not sufficient in php or Docker to pin-point the issue any further. If you need more information please just let me know.

> 
TASK [run composer] ************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist", "delta": "0:00:05.105378", "end": "2016-10-20 18:03:38.780586", "failed": true, "rc": 1, "start": "2016-10-20 18:03:33.675208", "stderr": "Loading composer repositories with package information\nInstalling dependencies from lock file\nGenerating optimized autoload files\n> Incenteev\\ParameterHandler\\ScriptHandler::buildParameters\n> Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap\n> Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache\nScript Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache handling the post-cmd event terminated with an exception\n\n                                                                                                                          \n  [RuntimeException]                                                                                                      \n  An error occurred when executing the \"'cache:clear --no-warmup'\" command:                                               \n                                                                                                                          \n    [Doctrine\\DBAL\\DBALException]                                                                                         \n    The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection().    \n                                                                                                                          \n  .                                                                                                                       \n                                                                                                                          \n\ninstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...", "stdout": "Updating the \"app/config/parameters.yml\" file\n\n                                                                                                                      \n  [Doctrine\\DBAL\\DBALException]                                                                                       \n  The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection().  \n                                                                                                                      ", "stdout_lines": ["Updating the \"app/config/parameters.yml\" file", "", "                                                                                                                      ", "  [Doctrine\\DBAL\\DBALException]                                                                                       ", "  The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection().  ", "                                                                                                                      "], "warnings": []}
NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/etc/ansible/entrypoint.retry
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1

**Comment by xsteadfastx** [comment]
i wish i would know what the failure means 

```
The options 'driver' or 'driverClass' are mandatory if no PDO instance is given to DriverManager::getConnection().
```
i will investigate more.

**Comment by xsteadfastx** [comment]
ok i guess i found something. it has to do with the ansible entrypoint and that it doesnt have defaults if no env variables get defined. trying to fix it right now.

**Comment by m0** [comment]
As far as I understand, this fix is included in the hub.docker.com image tagged as "latest", but not the one tagged as 2.1.2. If the tag reflects the wallabag version the fixed image should be tagged as 2.1.2 on docker hub.

**Comment by xsteadfastx** [comment]
also its tested now through 92f5db7ba904b242b2b934dbd53b6d5f84bbc9ee.

**Comment by xsteadfastx** [comment]
@m0 tag is updated and its building right now on docker hub
