### ISSUE TITLE
"Unknown error: Connection reset" when connecting to Wallabag Docker behind Traefik

### ISSUE THREAD

**Issue by sethsimmons** [wallabag/docker#263]
Copied from https://github.com/wallabag/android-app/issues/1150:
# Issue details

### Duplicate?
Yes:

https://github.com/wallabag/android-app/issues/997
https://github.com/wallabag/android-app/issues/911

### Actual behaviour
- Android app gives "Unknown error: Connection reset" when attempting to connect, but web behaves properly.

### Expected behaviour
- Android app should be able to login/autofill properly.

# Steps to reproduce the issue
1. Run Wallabag via Docker Compose with Traefik SSL redirection
  a. Relevant Traefik configs
  b. 
  ```56     labels:
 57       - "traefik.enable=true"
 58       - "traefik.http.routers.wallabag.rule=Host(`${WALLABAG_HOSTNAME}`)"
 59       - "traefik.http.routers.wallabag.middlewares=wallabag"
 60       - "traefik.http.routers.wallabag.entrypoints=websecure"
 61       - "traefik.http.routers.wallabag.tls.certresolver=selfhostedservices"
 64       - "traefik.http.middlewares.wallabag.headers.customRequestHeaders.X-Forwarded-Proto=https"
 ```
2. Validate that web login works properly
3. Attempt to login/connect via the Android app

# Environment details
- **wallabag app version**: 2.4.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid
- **Android OS version**: 11
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): CalyxOS
- **Android hardware**: Pixel 4A
- **wallabag server version**: wallabag/wallabag:latest (Docker)
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

n/a

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

```
wallabag        | 172.29.0.2 - - [07/Apr/2021:00:47:28 +0000] "GET / HTTP/1.1" 302 215 "-" "okhttp/4.9.0"
wallabag        | 172.29.0.2 - - [07/Apr/2021:00:47:29 +0000] "GET / HTTP/1.1" 302 215 "-" "okhttp/4.9.0"
```

Curl showing redirect to http for some reason:

```
curl -I https://wallabag.domain.com
HTTP/2 302
cache-control: max-age=0, must-revalidate, private
content-type: text/html; charset=UTF-8
date: Wed, 07 Apr 2021 00:47:55 GMT
expires: Wed, 07 Apr 2021 00:47:55 GMT
location: http://wallabag.domain.com/login
server: nginx
set-cookie: PHPSESSID=6004cd91853f8a9abffeda383e60874c; path=/; HttpOnly
```

# Docker Compose env variables
WALLABAG_HOSTNAME=wallabag.domain.com
WALLABAG_URL=https://wallabag.domain.com

**Comment by sethsimmons** [comment]
Any other info I can provide to make progress on this?

**Comment by ratheile** [comment]
I am also working on this problem. What I found out is that from the traefik container, i get redirected to 443 (https):

```
/ # wget 127.22.0.8:80
Connecting to 127.22.0.8:80 (127.22.0.8:80)
Connecting to 127.22.0.8 (127.22.0.8:443)
ssl_client: 127.22.0.8: name `127.22.0.8' not present in server certificate
wget: error getting response: Connection reset by peer
```

**Comment by sethsimmons** [comment]
Resolved this by adding HTTP to HTTPS redirects to Traefik configs:

```
 14       - "--entrypoints.web.address=:80"
 15       - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
 16       - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
 ```
 
 Also noticed issues with using a VPN that enforces strict HTTPS-only mode.
