### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by ngosang** [wallabag/docker#269]
Wallabag Docker image size **uncompressed** is 574 MB
According to [dive](https://github.com/wagoodman/dive) the image can be reduced at least in 100 MB.

I have some ideas but I'm not expert in php/composer:
* Why do you install Python and Python libraries? It takes ~188MB
* Remove `/root/composer/` I think this is the composer cache ~43 MB
* Remove `.git` folder (repository history) in the final image. I think it will be wise to remove all but the php source code and config.
* Is it possible to uninstall composer and other dependencies after the installation is complete? (I think you only need php, php-libs and nginx)
* Vendor folder is ~104MB. Are all dependencies required?

Update: If you don't agree, another alternative is to publish 2 images (with different tags). I think the slim image could be 1/3 the size of the current image with the same features (redis). Some of us are running Wallabag in RaspberryPi with low resources. :)

**Comment by Kdecherf** [comment]
Hello @ngosang,

You should definitely take a look at https://github.com/wallabag/docker/pull/256 :)

**Comment by ngosang** [comment]
Thank you, I will.
Just for reference. This app uses same technologies Php+Mysql and the image is just 50MB uncompressed / 20MB compressed:
https://hub.docker.com/r/kanboard/kanboard/
https://github.com/kanboard/kanboard/blob/master/Dockerfile

**Comment by Kdecherf** [comment]
Well it's not relevant to compare these two projects as they don't have the same amount of dependencies nor features.

**Comment by ngosang** [comment]
Fixed in the linked PRs.
