### ISSUE TITLE
automatic build for official image

### ISSUE THREAD

**Issue by Monirzadeh** [wallabag/docker#279]
is it possible for you to automatically build official docker image? (it is for 7 month ago)
it can build for each week or even last commit on master with specific tag.
we can have even stable and git version build.

**Comment by Kdecherf** [comment]
@Monirzadeh Hello, we don't support running wallabag on the master branch, we only build images that follow wallabag releases.

**Comment by jtagcat** [comment]
Build it yourself. If you blindly want to build a branch, use https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by Monirzadeh** [comment]
thanks i will build that myself.
