### ISSUE TITLE
Ansible script failure restarting container on MariaDB

### ISSUE THREAD

**Issue by shikasta-net** [wallabag/docker#281]
Hi, I don't think this is a duplicate issue but it's one I have had happen twice now.

When starting up the container from cold (with data but not resuming a stopped one; the database container is running already) the Ansible script chokes as follows:
`FAILED! => 
{"changed": false, "msg": "unable to parse the MySQL grant string: SET DEFAULT ROLE '0' FOR 'wallabag'@'%'"}`
I'm using mariadb 10.2 image, and Wallabag 2.4.2 image.

In case anyone else comes across this, the fix is to go into the database and run `SET DEFAULT ROLE NONE FOR 'wallabag'@'%'`, for your instance's database user.  Or set POPULATE_DATABASE=False in the environment.

I'll look into it further and see if I can work out why Ansible is failing and if I can post a fix.

**Comment by j0k3r** [comment]
Ansible has been replaced by shell script few days ago https://github.com/wallabag/docker/pull/307, so I'm closing that issue.
