### ISSUE TITLE
Unable to import large files

### ISSUE THREAD

**Issue by gpapin** [wallabag/docker#29]
Hi all,

I switch from v1 to v2 and I said why not switching to a docker instance. When migrating my old data I've got this: 

![capture d ecran 2016-11-04 16 30 04](https://cloud.githubusercontent.com/assets/3064311/20013955/02d0000e-a2ad-11e6-9252-f91daafb0487.png)

So I started to investigate if the limit was set your end or on the reverse proxy I've put on top of this installation. Turn out that doing that I've found this in your php.ini:

```
post_max_size = 20G
upload_max_filesize = 20G
```
given that you also have ```max_file_uploads = 20``` you could theoretically send 400GB to the server in a single request ! This will make you much more vulnerable to a DOS and there isn't really a use case for it... or is it ????

**Comment by j0k3r** [comment]
:flushed:

**Comment by gpapin** [comment]
Turns out this isn't anything to do with my reverse proxy since I have the same error while accessing the service directly. That would indicate that you can't upload 20G files but I still have to figure out why I can't go beyond 2MB 

- still this setting is confusing

**Comment by gpapin** [comment]
For reference my json is only 5MB so way bellow what nginx should be able to handle...

**Comment by nsteinmetz** [comment]
Did you look on nginx side to ``client_max_body_size``, it can also limit upload.

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by xsteadfastx** [comment]
`client_max_body_size` is set in the docker image. mmhhh thats strange. but first i created a PR that limit all uploads to 100M... for discussion.

**Comment by xsteadfastx** [comment]
@gpapin is there anything in the nginx logs?

**Comment by gpapin** [comment]
Here is the logs from ```docker logs wallabag```

```
::ffff:172.18.0.9 - - [07/Nov/2016:09:30:44 +0000] "POST /import/wallabag-v1 HTTP/1.1" 500 4303 "https://wallabag.privateweb.fr/import/wallabag-v1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
::ffff:172.18.0.9 - - [07/Nov/2016:09:30:45 +0000] "GET /bundles/wallabagcore/themes/material/css/style.min.css HTTP/1.1" 200 156438 "https://wallabag.privateweb.fr/import/wallabag-v1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
::ffff:172.18.0.9 - - [07/Nov/2016:09:30:45 +0000] "GET /bundles/wallabagcore/themes/_global/img/logo-other_themes.png HTTP/1.1" 200 3058 "https://wallabag.privateweb.fr/import/wallabag-v1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
```

**Comment by xsteadfastx** [comment]
ok... i think i found something. the location of the php.ini changed to /etc/php7 and this causes the problem. i will try to fix it right now.

**Comment by gpapin** [comment]
Ah yes that would make sense ! :)

**Comment by xsteadfastx** [comment]
sooo f7bd58c73afcd6dee74e6464f0b2d00c62de529a should have fixed this. docker hub is building right now.

**Comment by gpapin** [comment]
you are a legend :)
I can confirm that this is working, thanks !

**Comment by xsteadfastx** [comment]
yay :+1:
