### ISSUE TITLE
Docker compose error in mariadb container

### ISSUE THREAD

**Issue by GabrieleV** [wallabag/docker#295]
The DB container started using the sample docker.composer file, des not start.
Due to the use of mysqlping hin the healthceck, the command cannot run because it has not passowrd.
You have to add this line:

```
...
  wallabag_db:
...
    environment:
,,,,
      - MYSQL_PWD=wallaroot
,,,
```

**Comment by j0k3r** [comment]
As defined in the readme, you should define the `MYSQL_ROOT_PASSWORD`
https://github.com/wallabag/docker#mariadb--mysql
