### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by xsteadfastx** [wallabag/docker#3]
Add support for postgresql.

**Comment by nsteinmetz** [comment]
Hi @xsteadfastx, 

I have about the same idea.

Do you need some help or something ? 

I'll be off next week but I can have a look at it once I'm back.

Let me know,
Nicolas

**Comment by xsteadfastx** [comment]
yeah cool :) i wanted to do it today. i hope i dont run into problems :)

**Comment by xsteadfastx** [comment]
added :)

https://github.com/wallabag/docker/commit/06af34012318268ab7f590c063a73cccf7d0d808

**Comment by nsteinmetz** [comment]
Just tested, it works like a charm - thanks a lot !

**Comment by xsteadfastx** [comment]
On Sat, 30. Apr 12:22, Nicolas Steinmetz wrote:
> Just tested, it works like a charm - thanks a lot !

thats cool :) i use mariadb as backend so its nice that people actually
use this image with postgres.
