### ISSUE TITLE
Replace Ansible with Bash script

### ISSUE THREAD

**Issue by ngosang** [wallabag/docker#303]
Removing the Ansible and Python packages from the Dockerfile:
* We reduce the Docker image in 413 MB (595 MB -> 182 MB)

Converting the Ansible playbook into a Bash script:
* We keep the same functionality
* The Docker container startup time is reduced in +30 seconds

I can do the changes if you merge my other PRs first.

Related #269 #270

**Comment by j0k3r** [comment]
What do you think @wallabag/core?

**Comment by nicosomb** [comment]
I think it should be a good idea and a good optimization. 💯

**Comment by ngosang** [comment]
Ok, I will work on it this weekend.

Take a look and merge #265 #301 #302
