### ISSUE TITLE
How can I change the table prefix in docker container?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [wallabag/docker#304]
I have installed version 2.3.8 (non container) on a shared host; now I'm trying to run a local docker container, and update WB to the latest version. 

I have imported the db w/out issue, but whjen starting the container I get the error:

>  [error] 268#268: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_internal_setting' doesn't exist in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129

This led me to a rabbit hole search, of which first let me to updating version by version. So I set the container to pull version 2.4.0, and also read to run this command:

`/var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction`

which gave me an error:

![image](https://user-images.githubusercontent.com/39491297/198492244-2363c974-e97f-417d-b87e-862813ed385a.png)

THEN, I noticed that for whatever reason, when I installed WB on my shared host, it set the table prefix to `wlqm`, and the updater is looking for the table prefix `wallabag`.

NOW I don't know how to tell the container to use my prefix.

I went looking ALL over the net with no luck, so I dug into the `parameters.yml` file and saw it had a setting named `DATABASE_TABLE_PREFIX`, soooooo, I tried adding `SYMFONY__ENV__DATABASE_TABLE_PREFIX: 'wlqm'`  environment variable... still tries to use the 'wallabag' prefix when running the update command.

I've even tried mounting the `parameters.yml` to manually change the setting, but then I get another error about the container not being able to move a tmp file or something.

So, here I am. Ripping my hair out, lol. Does anyone know how to sort this out?

thanks!

**Comment by j0k3r** [comment]
I transferred the issue to the right repo.
And yes it seems we can't override the prefix when using the container.

You then have three options:
- rename the table in your dumped SQL schema so that the prefix will be `wallabag_` instead of `wlqm_`
- wait for 2.6.0 release to use the new docker version (with #305 merged)
- build your own image from master (once #305 is merged)

**Comment by YouveGotMeowxy** [comment]
Happy to report that replacing `wlqm` with `wallabag` and then running the migrate command above fixed it all (i _think_?)

I then moved to the `latest` tag and when trying to add [this page](https://heavy.com/news/orlando-harris/), I get a SQL error:

```
500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, hashed_url, origin_url, given_url, hashed_given_url, is_archived, archived_at, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params

<SNIP>

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xBA\xF0\x9F...' for column `wallabag`.`wallabag_entry`.`content` at row 1
```

Is this happening only to my instance?
