### ISSUE TITLE
wallabag can't runing

### ISSUE THREAD

**Issue by DukeFox** [wallabag/docker#316]
I get an error when I use the following command
```
$ docker run -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag
```
error log：
```
  PDO Driver (pdo_sqlite)   OK!                                                                                                                         
  Database connection       ERROR!   Can't connect to the database: An exception occurred in driver: SQLSTATE[HY000] [14] unable to open database file  
  Database version          OK!                                                                                                                         
  curl_exec                 OK!                                                                                                                         
  curl_multi_init           OK!                                                                                                                         
 ------------------------- -------- ------------------------------------------------------------------------------------------------------------------- 

12:29:16 ERROR     [console] Error thrown while running command "wallabag:install --env=prod -n". Message: "Some system requirements are not fulfilled. Please check output messages and fix them." ["exception" => RuntimeException { …},"command" => "wallabag:install --env=prod -n","message" => "Some system requirements are not fulfilled. Please check output messages and fix them."]

In InstallCommand.php line 163:
                                                                               
  Some system requirements are not fulfilled. Please check output messages an  
  d fix them.                                                                  
                                                                               

wallabag:install [--reset] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] 
```

It works fine if I use the following command
```
$ docker run  -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag
```

How to fix it?

**Comment by j0k3r** [comment]
Does `/opt/wallabag/data` is writable?

**Comment by DukeFox** [comment]
> Does `/opt/wallabag/data` is writable?

yes, 755/root

**Comment by DukeFox** [comment]
```
-v /opt/wallabag/images:/var/www/wallabag/web/assets/images
```
After enable local caching of images, there are no files inside this mapped directory either.

**Comment by xcojonny** [comment]
Same here.

**Comment by df911** [comment]
same problem here

**Comment by carlosmandel** [comment]
I have the same problem. On macOS using Docker Desktop, I managed to fix this issues by creating a `db` directory inside the hosts directory, but that doesn't work on my Linux host.

**Comment by laurentlbm** [comment]
Found the issue. The data directory must be mounted to `/var/www/wallabag/web/data`, not `/var/www/wallabag/data`.

**Comment by j0k3r** [comment]
Hum it's weird.
The web folder means it'll be accessible to the world. The data folder shouldn't be accessible.

**Comment by laurentlbm** [comment]
You're right, I was wrong. I'll investigate a bit more.

**Comment by laurentlbm** [comment]
Upon investigation, the problem seems to be that it tries and fails to create the file `/var/www/wallabag/data/db/wallabag.sqlite`.

It can fail for 2 reasons:
1. It requires the sub-directory `db` to already exist.
2. It tries to create the SQLite file as the user `nobody` and fails unless that user has write-access to the `db` directory.

**Comment by igvr** [comment]
bump.

tried creating `db/` and` db/wallabag.sqlite`
with `chmod -R /var/www/wallabag/`

**Comment by ozls** [comment]
Solved it by (1) first creating the `data` folder and its `db` subfolder (2) doing `sudo chown nobody data --recursive`

**Comment by AdrianEarnshawMusic** [comment]
Same issue here, cannot seem to get the db to create. I’m on a Synology box and ozls workaround didn’t fix it for me. Ended up going down the mariadb route but would rather have SQLite.

**Comment by Valkann** [comment]
> Same issue here, cannot seem to get the db to create. I’m on a Synology box and ozls workaround didn’t fix it for me. Ended up going down the mariadb route but would rather have SQLite.

I sucess to launch with SQLite on Synology with this Workaround: 

``` 
chown -R nobody /volume1/docker/wallabag
chmod -R 777 /volume1/docker/wallabag
```
