### ISSUE TITLE
JSON export to Wallabag v2 import from 2.4.2 to 2.5.3 fails

### ISSUE THREAD

**Issue by baloan** [wallabag/docker#317]
Migrating my wallabag instance is an adventure. 
**Attempt 1:** export all articles, then import using the wallabag v2 importer
On import I get this error message `This form should not contain extra fields.`. Nothing is imported.
**Attempt 2:** copying the database from 2.4.2 to 2.5.3
I've noted that the table prefix has changed from _wg__ to _wallabag__ - and gave up.
On both databases the latest entry in _migration_versions_ is 20200428072628.
What is the recommended way to migrate data across instances?

**Comment by keithmillar** [comment]
I to have this issue

**Comment by j0k3r** [comment]
> I've noted that the table prefix has changed from _wg__ to _wallabag__ - and gave up.

The prefix hasn't changed, it's a config: https://github.com/wallabag/docker/blob/185b063ca2af24ccdabfec04d607fed75fde8190/root/etc/wallabag/parameters.template.yml#L9

> On import I get this error message `This form should not contain extra fields.`. Nothing is imported.

That error is weird.
I've you tried to logout, login back and retry?

> What is the recommended way to migrate data across instances?

Exporting/importing is a good solution.
Copy/pasting database is an other one too.

From what wallabag instance are you migrating and to what instance?

**Comment by keithmillar** [comment]
I updated  so that both version of wallabag where the same 2.5.3 the json file would still not import. I then copied the database over and this worked.

**Comment by baloan** [comment]
I exported the database, in the resulting sql did a global search replace from wb_ to wallabag_, then imported the sql. That worked without issues. 

> From what wallabag instance are you migrating and to what instance?
2.4.2 to 2.5.3

**Comment by renaldofreire** [comment]
I'm having the same error.  Has anyone managed to resolve?

**Comment by mattconnell** [comment]
I was also in the position of trying to migrate from sqlite to postgres and got hung up by the bug mentioned by @Fischmiep 

I wasn't willing to wait for a fix to the importer, so [I wrote my own](https://gist.github.com/mattconnell/93099b36fa60e77cc917fc81b84e3580).  This simple script can digest the exported wallabag JSON and issue API requests to import them.  It ain't pretty, and it ain't fast, but it seems accurate so far.  Tags are preserved/created, archive/star status is kept, etc.  I don't use annotations so I can't test that, but I can say my current code doesn't account for them.

Critique is welcome, this was written hastily so I'm certain it could be improved.

**Comment by Fischmiep** [comment]
Considering that the image has been updated to 2.6.x a while ago, this issue should be fixed. @j0k3r I suggest closing this issue for now. People can re-open it if there are still issues with this.
