### ISSUE TITLE
Error in menu text

### ISSUE THREAD

**Issue by JuanRodenas** [wallabag/docker#321]
Hello,

Can you correct or tell me how to correct what I indicate in the screenshots?

![picture1](https://user-images.githubusercontent.com/95724863/217964888-13630f42-5762-4880-a90f-965673b3149b.png)
![picture2](https://user-images.githubusercontent.com/95724863/217964894-58a589f1-adaf-4c2a-bdff-a32ff7739b5e.png)

Best regards,
Juan

**Comment by j0k3r** [comment]
Looks like the translation is missing.
As stated in the [README of the main repo](https://github.com/wallabag/wallabag#translation), you can fix translation on Weblate: https://hosted.weblate.org/projects/wallabag/

**Comment by j0k3r** [comment]
Which version of wallabag are you installing?

**Comment by JuanRodenas** [comment]
Hi, I am using the latest version of Wallabag.

**Comment by j0k3r** [comment]
This is weird. What language?

**Comment by JuanRodenas** [comment]
Spanish

**Comment by Kdecherf** [comment]
These translations were introduced by 519e9db94b92965968a188beb8d44c161174a33e on Dec, 4th 2022.
These changes are not included in a release yet, it should be the case in the next 2.6.0 version.

**Comment by JuanRodenas** [comment]
Hello!
Thank you very much for the reply, we are waiting impatiently for the translations.
Best regards.
