### ISSUE TITLE
 Plan from migrating away from dockerhub? 

### ISSUE THREAD

**Issue by hydrargyrum** [wallabag/docker#326]
Wallabag's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/). Do you have any plans for migrating hosting elsewhere?

**Comment by j0k3r** [comment]
> As of March 24, 2023, Docker has reversed its decision to sunset the “Docker Free Team” plan. Read on for details.

https://www.docker.com/developers/free-team-faq
