### ISSUE TITLE
Access Denied After Upgrade / Reinstall (Docker)

### ISSUE THREAD

**Issue by anotherprivuser** [wallabag/docker#339]
After updating wallabag in docker I receive an access denied for user wallabag when trying to connect and migrate. Foolishly I attempted to reinstall a new instance but was unable to successfully launch it, so I reinstalled wallabag with the original db and updated it and cannot access or migrate it; I used the same compose file from the original install.

### **Compose File**

version: '3.9'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: Wallabag
    restart: on-failure:5
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=http://YourServerHere
      - SYMFONY__ENV__SERVER_NAME=YourServerHere
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__TWOFACTOR_AUTH=true
    ports:
      - 6749:80
    volumes:
      - /volume1/docker/wallabag/images:/var/www/wallabag/web/assets/images:rw
      - /volume1/docker/wallabag/data:/var/www/wallabag/data:rw
     
    depends_on:
     - db
     - redis
  db:
    image: mariadb
    container_name: Wallabag-DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - TZ=YourTZHere
    volumes:
      - /volume1/docker/wallabagdb:/var/lib/mysql:rw
 redis:
    image: redis:alpine
    container_name: Wallabag-REDIS
    restart: on-failure:5

### **Log**
      
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In Driver.php line 34:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In ExceptionConverter.php line 101:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [1044] Access denied f  
  or user 'wallabag'@'%' to database 'wallabag'                                
                                                                               
In Exception.php line 28:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In Driver.php line 34:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
 [WARNING] Some commands could not be registered:                               
In ExceptionConverter.php line 101:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [1044] Access denied f  
  or user 'wallabag'@'%' to database 'wallabag'                                
                                                                               
In Exception.php line 28:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In Driver.php line 34:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In ExceptionConverter.php line 101:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [1044] Access denied f  
  or user 'wallabag'@'%' to database 'wallabag'                                
                                                                               
In Exception.php line 28:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In Driver.php line 34:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In ExceptionConverter.php line 101:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [1044] Access denied f  
  or user 'wallabag'@'%' to database 'wallabag'                                
                                                                               
In Exception.php line 28:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
In Driver.php line 34:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user 'wallabag'@'%' to database 'w  
  allabag'                                                                     
                                                                               
 Trying to install assets as relative symbolic links.

          Bundle                   Method / Error    
  ✔   NelmioApiDocBundle       relative symlink  
  ✔   CraueConfigBundle        relative symlink  
  ✔   BabDevPagerfantaBundle   relative symlink  
  ✔   FOSJsRoutingBundle       relative symlink  
 --- ------------------------ ------------------ 
 [OK] All assets were successfully installed.                                   
wallabag is ready!

**Comment by dannykorpan** [comment]
Same problem here, after update.

**Comment by Zayon** [comment]
I also could not connect since I pulled the new image version.

Relevant logs:

```
security.INFO: Authentication request failed. {"exception":"[object] 
(Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): 
An exception occurred while executing a query: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't20.display_thumbnails' in 'field list' 
at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:96 [...]
```

### How I fixed it

**:warning: backup your database before !**

``` 
docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:sync-metadata-storage
docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:migrate
```

**Comment by dannykorpan** [comment]
> I also could not connect since I pulled the new image version.
> 
> Relevant logs:
> 
> ```
> security.INFO: Authentication request failed. {"exception":"[object] 
> (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): 
> An exception occurred while executing a query: 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 't20.display_thumbnails' in 'field list' 
> at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:96 [...]
> ```
> 
> ### How I fixed it
> **⚠️ backup your database before !**
> 
> ```
> docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:sync-metadata-storage
> docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:migrate
> ```

Works, thank you for the workaround!

**Comment by anotherprivuser** [comment]
Tried to execute the above, however, @dannykorpan @Zayon the error you received is 1054 Unknown column , the error I receive is 1044 Access Denied.

### Code
docker exec -it -w /var/www/wallabag Wallabag bin/console -e prod doctrine:migrations:sync-metadata-storage
### Result
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/Wallabag/json": dial unix /var/run/docker.sock: connect: permission denied

### Code
docker exec -it -w /var/www/wallabag Wallabag bin/console -e prod doctrine:migrations:migrate
### Result
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/Wallabag/json": dial unix /var/run/docker.sock: connect: permission denied

I've tried connecting directly to the mariadb and executing the GRANT ALL privileges to the wallabag user to no avail - the credentials are identical to the original install, yet does not work after reinstalling wallabag with the orginal db.

Any recommendations to recover and migrate the db to a fresh install?

**Comment by anotherprivuser** [comment]
### Update:

**executed** chown -R 999:999 on wallabag and wallabag
**Result**: Access denied error fixed

**executed** docker exec -it -w /var/www/wallabag Wallabag bin/console -e prod doctrine:migrations:sync-metadata-storage
**Result**:SQLSTATE[42S02]: Base table or view not found: 1932 Table 'wallabag.migration_versions' doesn't exi
  st in engine

**executed** docker exec -it -w /var/www/wallabag Wallabag bin/console -e prod doctrine:migrations:migrate
**Result**: SQLSTATE[42S02]: Base table or view not found: 1932 Table 'wallabag.wallabag_internal_setting' doesn't exist in engine

Any recommendations to fix error SQLSTATE[42S02] or am I hooped and should just reinstall and recover/migrate the db to a fresh install?

**Comment by anotherprivuser** [comment]
It is working now, Thank you for the help. 
Here is how I resolved the issue.

**The issue**
permission denied on docker.sock
Fix: `sudo chown 666 /var/run/docker`

**Migrated db with**
```
docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:sync-metadata-storage
docker exec -it -w /var/www/wallabag <container_name> bin/console -e prod doctrine:migrations:migrate
```
