### ISSUE TITLE
Does not perform database upgrade on update from 2.x to 2.1

### ISSUE THREAD

**Issue by ViViDboarder** [wallabag/docker#34]
I had to do this manually. It seems like something that Ansible could do since it runs the playbook every time the container starts.

**Comment by ViViDboarder** [comment]
I suppose this could also be handled by the web application as well.

**Comment by xsteadfastx** [comment]
i agree that it would be the best to do in the web application. right now i didnt found a way to check the current version and the db version to run the command if its needed.

**Comment by j0k3r** [comment]
Migrate command has been added in https://github.com/wallabag/docker/pull/48

**Comment by ViViDboarder** [comment]
Great patch. That's certainly useful for what I was suggesting here, but I
was wondering why one would need to run the migrate command themselves at
all. Couldn't the Ansible playbook check the database version and run
migrate on a standard run?

This resolved situations where users are unsure when an update requires a
migration.

**Comment by xsteadfastx** [comment]
i think its pretty dangerous to run the migrations all the time. i didnt
found a way how to find out what version the db is... maybe someone has
an idea.
