### ISSUE TITLE
Docker image for 2.6.3 is missing

### ISSUE THREAD

**Issue by jurgenhaas** [wallabag/docker#364]
Is that delay on purpose or is the build process broken?

**Comment by nicosomb** [comment]
https://hub.docker.com/layers/wallabag/wallabag/2.6.3/images/sha256-affff50c1526b56c27b24b691cb28282ecf332696f951221bf1cf72d74cf66bf?context=explore

**Comment by jurgenhaas** [comment]
No worries, thank you so much for your very quick response.
