### ISSUE TITLE
Upgrade Ubuntu in docker image

### ISSUE THREAD

**Issue by nicosomb** [wallabag/docker#368]
Is there plans to upgrade the old Ubuntu 16.04 the Docker image is still based on?

_Originally posted by @romu70 in https://github.com/wallabag/wallabag/discussions/6177#discussioncomment-6809773_

**Comment by romu70** [comment]
It's maybe a big task, but is moving to a more lightweight distro like Alpine feasible?

**Comment by nicosomb** [comment]
Already done :) 
https://github.com/wallabag/wallabag/discussions/6177#discussioncomment-6809945
