### ISSUE TITLE
Wallabag Installation not displaying in browser

### ISSUE THREAD

**Issue by mrtargaryen** [wallabag/docker#389]
Hi.

I'm pretty new to docker, still learning.

I created a .yml file for docker compse and entered the following:

> version: '3'
> services:
>   wallabag:
>     image: wallabag/wallabag
>     environment:
>       - MYSQL_ROOT_PASSWORD=wallaroot
>       - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
>       - SYMFONY__ENV__DATABASE_HOST=db
>       - SYMFONY__ENV__DATABASE_PORT=3306
>       - SYMFONY__ENV__DATABASE_NAME=wallabag
>       - SYMFONY__ENV__DATABASE_USER=wallabag
>       - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
>       - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
>       - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
>       - SYMFONY__ENV__MAILER_DSN=smtp://my@email:password@smtp.mail.me.com:587
>       - SYMFONY__ENV__FROM_EMAIL=my@email
>       - SYMFONY__ENV__DOMAIN_NAME=http://192.168.50.6
>       - SYMFONY__ENV__SERVER_NAME="my wallabag"
>     ports:
>       - "80"
>     volumes:
>       - /opt/wallabag/images:/var/www/wallabag/web/assets/images
>     healthcheck:
>       test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
>       interval: 1m
>       timeout: 3s
>     depends_on:
>       - db
>       - redis
>   db:
>     image: mariadb
>     environment:
>       - MYSQL_ROOT_PASSWORD=wallaroot
>     volumes:
>       - /opt/wallabag/data:/var/lib/mysql
>     healthcheck:
>       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
>       interval: 20s
>       timeout: 3s
>   redis:
>     image: redis:alpine
>     healthcheck:
>       test: ["CMD", "redis-cli", "ping"]
>       interval: 20s
>       timeout: 3s

I successfully installed Wallabag and created an account

But this is what I see once logged in:

https://i.imgur.com/f4ryRmn.png

I'm not sure what I've done wrong, any ideas?

**Comment by mrtargaryen** [comment]
Any ideas why Wallabag doesn't display in any browser like this?

**Comment by tp0s** [comment]
add the host port to symfony_env_domain_name. 

- SYMFONY__ENV__DOMAIN_NAME=http://192.168.50.6:**8081** or whatever port you have exposed

**Comment by mrtargaryen** [comment]
> add the host port to symfony_env_domain_name. 
> 
> 
> 
> - SYMFONY__ENV__DOMAIN_NAME=http://192.168.50.6:8081 or whatever port you have exposed
> 
> 

Solved, thanks!
