### ISSUE TITLE
Problems importing many articles from Pocket

### ISSUE THREAD

**Issue by goncalor** [wallabag/docker#39]
I just cloned and built the wallabag image from the HEAD of this repository. I simply ran it with

`docker run -ti -p 80:80 wallabag`

then logged in an tried to import from a Pocket account with 600 articles. After 60 seconds the browser showed `504 Gateway Time-out` coming from Nginx. I figured this should be due to FastCGI's timeout and added the following under `http` in `/etc/nginx/nginx.conf`

`fastcgi_read_timeout 300;`

I ran wallabag again. No more HTTP 504. But now, after about 2 minutes of clicking the import button there's an error coming from wallabag

```
500: Internal Server Error
Attempted to call function "gzuncompress" from the global namespace.
```

What does this error mean? I couldn't find information about it. Is there some other configuration in the container I should change for a somewhat big import like this?

Thank you.

PS: refreshing wallabag it shows a total of 80 articles.
PS2: I tried setting `gzip` to `off` in `nginx.conf` but it didn't help.

**Comment by xsteadfastx** [comment]
you should link to a redis container for import.

```
$ docker run -p 6379:6379 --name redis redis:alpine
$ docker run -p 80:80 --link redis:redis wallabag/wallabag
```

**Comment by goncalor** [comment]
Thank you for your reply! I managed to do it. I will sum up here what I did in hope it helps someone else.

Run a Redis container along with wallabag as suggested by @xsteadfastx . Then activate the Redis import under `Internal Settings > Import` (by setting the option to 1). And then click the import button for Pocket in the `Import` menu.

The Redis container outputs something like this

```
1:M 30 Nov 23:49:05.769 * 100 changes in 300 seconds. Saving...
1:M 30 Nov 23:49:05.769 * Background saving started by pid 11
11:C 30 Nov 23:49:05.828 * DB saved on disk
11:C 30 Nov 23:49:05.828 * RDB: 0 MB of memory used by copy-on-write
1:M 30 Nov 23:49:05.869 * Background saving terminated with success
```

When you refresh wallabag it shows a message saying `Messages in queue: 601`. (Where 601 will be the number of articles you have in Pocket.)

The last step, as noted [here][doc-asynchronous-import], is to run the following command in the container where wallbag is running

```
/var/www/wallabag/bin/console wallabag:import:redis-worker -e=prod pocket -vv >> /var/www/wallabag/var/logs/redis-pocket.log
```

So you can open a shell in wallbag's container with the command below and then execute the command above there

```
docker exec -ti YOUR_CONTAINER_NAME sh
```

The import should begin and after a while you will have all your Pocket articles in wallabag :)

If you don't plan to do more imports you can now disable Redis and stop its container.

[doc-asynchronous-import]: http://doc.wallabag.org/en/2.2/developer/asynchronous.html#launch-redis-consumer

**Comment by xsteadfastx** [comment]
thank you @goncalor! maybe we should add this to the readme and link to the docs.
