### ISSUE TITLE
mailer_dsn urlencoding does not work - % gets pick up as another parameter

### ISSUE THREAD

**Issue by j-mir-prazak** [wallabag/docker#391]
It might not be bug, but a feature, but there seems to be some issue with the mailer_dns not working even with url encoding: the **%** sign seems to break the url into multiple parameters - and thus crashing the wallabag instance.

for some reason, if you use another **%** as escaping character, it does work and even the email works.

example: smtp://user:pass%%20word@smtp.gmail.com:587 would work with "pass word".

i did not seen it anywhere mentioned, so i just leave it here so someon can reference it at least
(it does not seem google app passwords will work otherwise, because they always have whitespace)

**Comment by j0k3r** [comment]
Good to know, maybe you can put a mention in the doc: https://github.com/wallabag/doc/blob/master/en/admin/mailer.md
