### ISSUE TITLE
deploy with fly.io get Invalid CSRF token error

### ISSUE THREAD

**Issue by zouyq** [wallabag/docker#397]
I deploy wallabag into fly.io with dockerfile,sometimes get `Invalid CSRF token`. when login;

![recording](https://github.com/wallabag/docker/assets/17286153/bc36c90f-d35b-437b-aa7a-a98f256a566b)

After completing the deployment, sometimes I can log in successfully for the first time. However, after successfully logging in and making some configuration changes, it automatically logs me out. Upon logging out, when I try to log in again by entering the username and password, it redirects back to the login page. Clicking again leads to an error: "Invalid CSRF token." Subsequently, I am unable to log in successfully. It's very strange.
this is my fly.io toml file
```
# fly.toml app configuration file generated for bag on 2024-01-26T08:51:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xxxx"
primary_region = "lax"

[build]

[env]
  SYMFONY__ENV__DOMAIN_NAME = "https://xxxx.fly.dev"

[http_service]
  internal_port = 80

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
```

**Comment by Kdecherf** [comment]
Hello @zouyq,

wallabag relies on session data for keeping users logged in and temp data like csrf tokens for forms. For that these data are either stored on the filesystem or in a cache system like redis.

You may need to check that the folder `var/sessions` is persisted on your Fly Machine to survive redeploy or restart.
