### ISSUE TITLE
gzuncompress error while importing from Pocket API or Instapaper csv

### ISSUE THREAD

**Issue by nicosomb** [wallabag/docker#40]
_From @itnAAnti on December 15, 2016 18:1_

### Issue details

When importing from Pocket via the API, or importing from an Instapaper csv file, I receive the error: **500: Internal Server Error Attempted to call function "gzuncompress" from the global namespace.**

### Environment
* Official Docker image, version 2.1.5
* Docker 1.11.2
* Running on an x86_64 Synology NAS (Linux NAS 3.10.77 #8451)
* PHP 5.6
* PostgreSQL

### Steps to reproduce/test case

1. Download / run latest Docker image, currently version 2.1.5
2. Download, link, run latest PostgreSQL Docker image, currently 9.6.1
3. Start both, verify Wallabag configured the DB ok and is running correctly
3. Get Pocket consumer key on your account and configure in Wallabag
4. Import from Pocket

_Copied from original issue: wallabag/wallabag#2705_

**Comment by itnAAnti** [comment]
I configured redis for async importing, and received the same error, but the logs had some additional information:

> [Symfony\Component\Debug\Exception\UndefinedFunctionException]        
  Attempted to call function "gzuncompress" from the global namespace.

> Exception trace:
 () at /var/www/wallabag/vendor/tecnickcom/tcpdf/include/tcpdf_filters.php:357
 TCPDF_FILTERS::decodeFilterFlateDecode() at /var/www/wallabag/vendor/tecnickcom/tcpdf/include/tcpdf_filters.php:94
 TCPDF_FILTERS::decodeFilter() at /var/www/wallabag/vendor/tecnickcom/tcpdf/tcpdf_parser.php:781
 TCPDF_PARSER->decodeStream() at /var/www/wallabag/vendor/tecnickcom/tcpdf/tcpdf_parser.php:702
 TCPDF_PARSER->getIndirectObject() at /var/www/wallabag/vendor/tecnickcom/tcpdf/tcpdf_parser.php:123
 TCPDF_PARSER->__construct() at /var/www/wallabag/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php:88
 Smalot\PdfParser\Parser->parseContent() at /var/www/wallabag/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php:74
 Smalot\PdfParser\Parser->parseFile() at /var/www/wallabag/vendor/j0k3r/graby/src/Graby.php:535
 Graby\Graby->handleMimeAction() at /var/www/wallabag/vendor/j0k3r/graby/src/Graby.php:188
 Graby\Graby->doFetchContent() at /var/www/wallabag/vendor/j0k3r/graby/src/Graby.php:143
 Graby\Graby->fetchContent() at /var/www/wallabag/src/Wallabag/CoreBundle/Helper/ContentProxy.php:51
 Wallabag\CoreBundle\Helper\ContentProxy->updateEntry() at /var/www/wallabag/src/Wallabag/ImportBundle/Import/AbstractImport.php:93
 Wallabag\ImportBundle\Import\AbstractImport->fetchContent() at /var/www/wallabag/src/Wallabag/ImportBundle/Import/PocketImport.php:205
 Wallabag\ImportBundle\Import\PocketImport->parseEntry() at /var/www/wallabag/src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php:50
 Wallabag\ImportBundle\Consumer\AbstractConsumer->handleMessage() at /var/www/wallabag/src/Wallabag/ImportBundle/Consumer/RedisEntryConsumer.php:18
 Wallabag\ImportBundle\Consumer\RedisEntryConsumer->manage() at /var/www/wallabag/vendor/javibravo/simpleue/src/Simpleue/Worker/QueueWorker.php:99
 Simpleue\Worker\QueueWorker->manageJob() at /var/www/wallabag/vendor/javibravo/simpleue/src/Simpleue/Worker/QueueWorker.php:68
 Simpleue\Worker\QueueWorker->start() at /var/www/wallabag/src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php:42
 Wallabag\ImportBundle\Command\RedisWorkerCommand->execute() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:254
 Symfony\Component\Console\Command\Command->run() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:837
 Symfony\Component\Console\Application->doRunCommand() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:118
 Symfony\Component\Console\Application->run() at /var/www/wallabag/bin/console:29

**Comment by itnAAnti** [comment]
I found a solution.

Edit /etc/php7/php.ini
Change line 271: 

> zlib.output_compression = Off 

Change it to:

> zlib.output_compression = On

Save and quit, and the import works properly.

**Comment by xsteadfastx** [comment]
So should we add this to the image?

**Comment by j0k3r** [comment]
Could be a great addition

**Comment by itnAAnti** [comment]
I don't have a full understanding of when gzuncompress is used during importing articles, but I will say that it fixed the import for me, and from what I have read enabling gzip is a relatively common configuration option in PHP, so I don't think there are significant side effects.

Bottom line, I recommend adding this to the image, but would defer to someone with a better understanding of the side effects.

**Comment by xsteadfastx** [comment]
sorry for my late response. i have some health issues the last week and wasnt on my computer much,
