### ISSUE TITLE
start container in read-only with bind volumes: `php-wallabag.template.ini` is missing

### ISSUE THREAD

**Issue by Bergruebe** [wallabag/docker#413]
Hello, I'm currently creating an [ansible-role](https://github.com/Bergruebe/ansible-role-wallabag) to run the wallabag container with the [mash-playbook](https://github.com/mother-of-all-self-hosting/mash-playbook).

This is my docker command
```bash
docker create \
                --rm \
                --name=mash-wallabag \
                --log-driver=none \
                --user=999:1001 \
                --cap-drop=ALL \
                --label-file=/mash/wallabag/config/labels \
                --network=mash-wallabag \
                --mount type=bind,src=/mash/wallabag/data,dst=/var/www/wallabag \
                --mount type=bind,src=/mash/wallabag/config/etc/wallabag,dst=/etc/ \
                --read-only \
                --tmpfs=/tmp:rw,noexec,nosuid,size=100m \
                --env-file=/mash/wallabag/config/env \
                docker.io/wallabag/wallabag:2.6.9
```

First I encounter this error:
```
/entrypoint.sh: line 30: can't open /etc/wallabag/parameters.template.yml: no such file
```
After manually coping [`root/etc/wallabag/parameters.template.yml`](https://github.com/wallabag/docker/blob/master/root/etc/wallabag/parameters.template.yml) from this git repo to `/mash/wallabag/config/etc/wallabag` on the server, I got the next error:

```
/entrypoint.sh: line 31: can't open /etc/wallabag/php-wallabag.template.ini: no such file
```

I can't finde the `php-wallabag.template.ini` file itself or it being mentioned somewhere in the `entrypoint.sh` script.

It would be great, if someone could give me a hint, where I'm stuck. 

https://github.com/Bergruebe/ansible-role-wallabag

**Comment by Kdecherf** [comment]
Hello @Bergruebe,

The file you're mentioning as been added in the branch 2.6.x but is not present in the main branch (which may be an issue), you can find it here: https://github.com/wallabag/docker/blob/2.6.x/root/etc/wallabag/php-wallabag.template.ini

**Comment by Bergruebe** [comment]
Thank you for your answer!

I actually stoped working on [ansible-role-wallabag](https://github.com/Bergruebe/ansible-role-wallabag), because I didn't got the container running. 
If someone is interested in finishing the role, feel free to open a PR!
