### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by paulr24** [wallabag/docker#425]
I am trying to get Wallabag running on my Synology NAS (Docker, MariaDB) but keep getting "500 Internal Server Error." I have my stack set as follows:

services:
  wallabag:
    image: wallabag/wallabag
    container_name: Wallabag
    restart: on-failure:5
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.2:6060
      - SYMFONY__ENV__SERVER_NAME=paulr24
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__FOSUSER_REGISTRATION=true
      - SYMFONY__ENV__TWOFACTOR_AUTH=true
    ports:
      - 6060:80
    volumes:
      - /volume1/docker/config/wallabag/images:/var/www/wallabag/web/assets/images:rw
      - /volume1/docker/config/wallabag/data:/var/www/wallabag/data:rw
    depends_on:
     - db
     - redis
  db:
    image: mariadb:11.4-noble #LTS Long Time Support Until May 29, 2029.
    container_name: Wallabag-DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - TZ=America/New_York
    volumes:
      - /volume1/docker/config/wallabag/db:/var/lib/mysql:rw
      
  redis:
    image: redis:alpine
    container_name: Wallabag-REDIS
    healthcheck:
     test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/config/wallabag/redis:/data:rw
    restart: on-failure:5

I have configured Synology's reverse proxy as well, but I don't believe that should affect this since for now I'm only trying to access it via the IP/port for now. Any ideas?

**Comment by j0k3r** [comment]
Have you checked wallabag logs inside the container in `/var/www/wallabag/var/logs/`?

**Comment by paulr24** [comment]
> Have you checked wallabag logs inside the container in `/var/www/wallabag/var/logs/`?

I'm fairly new to Docker and I don't have "/var/www/wallabag/var/logs" listed in my stack as a volume. Where might I find it?

I actually deleted and started over fresh, and now my Wallabag container fails to start and when I go to the container logs I see the following:

ERROR 2002 (HY000): Received error packet before completion of TLS handshake. The authenticity of the following error cannot be verified: 1130 - Host '172.26.0.4' is not allowed to connect to this MariaDB server

**Comment by euinor** [comment]
If you are using the Container Manager in your Synology go to Project -> Wallabag -> then click on each container then the tab 'log'. Check both the database logs and the wallabag logs.

**Comment by paulr24** [comment]
> If you are using the Container Manager in your Synology go to Project -> Wallabag -> then click on each container then the tab 'log'. Check both the database logs and the wallabag logs.

Ah, I knew how to do it that way, was just thrown off when you mentioned "/var/www/wallabag/var/logs." I actually ended up deleting the stack and adding it back, and it worked! Thank you!
