### ISSUE TITLE
Docker on Synology not working

### ISSUE THREAD

**Issue by magefesa** [wallabag/docker#50]
I have installed on Synology and i ve changed port, but not working... Other versions, like moritanosuke-wallabag works perfect. Any ideas please ?

**Comment by j0k3r** [comment]
What is not working? Did you have an error? How did you launch it?
Please give us more information instead of just saying "it's not working".

**Comment by xsteadfastx** [comment]
Did you recreated the container with the new port? 

Am 2. Februar 2017 05:07:17 MEZ schrieb magefesa <notifications@github.com>:

**Comment by magefesa** [comment]
First of all, really sorry. My poor explanation does not help to improve anything. 
So, i m gonna explain the problem :+1: 

Here is my settings on my Docker :+1: 
[https://d.pr/IGJe](url)

As you can see,  my local port is 8117, what I need is a different port than 80.

I ve another version of Wallabag running (not official) : See the screenshot :+1: 
[https://d.pr/Uvw](url)

This is working fine, but i would like to work with your distribution. 
Can you help me please ?

TYhanks in advance, and again, thanks for your support

**Comment by magefesa** [comment]
I ve updated the links, i don t know what happened.... Sorry again...

**Comment by xsteadfastx** [comment]
@magefesa what happens if you access your http://<synalogy>:8117? are there errors? the other screenshot is not working.

**Comment by magefesa** [comment]
Here is my screenshoot showing the error (page does not exist)
[http://d.pr/i/BtWZ](url)

Also, another screenshoot showing the setup 
[http://d.pr/i/ldtO](url)

Thanks in advance !
Any idea what is wrong ?

**Comment by xsteadfastx** [comment]
is there any way of running the docker container from a console? or to access the output from docker? its an 500 http error. so it looks like it can access it but something goes wrong. stupid question: did you try a completly fresh container? no old linked volumes or databases?

**Comment by magefesa** [comment]
Is there any way of running the docker container from a console?  _I dont know, i ll search for it !_ 
or to access the output from docker? _What do you mean ?_ 
 its an 500 http error. so it looks like it can access it but something goes wrong. stupid question: did you try a completly fresh container? _Its a fresh container_

**Comment by xsteadfastx** [comment]
the container logs its access logs and errors to stdout and stderr. we need this output to guess whats wrong. and did you try to start a fresh container? no links and everything. just ` docker run -p 80:80 wallabag/wallabag`. this should just works. maybe something is wrong with db you are try to use. first we need to check  what is wrong.

**Comment by magefesa** [comment]
Here is a report...does it help ?
[wallabag2_2_1.html.pdf](https://github.com/wallabag/docker/files/757897/wallabag2_2_1.html.pdf)

Come on guys ! Help me please ! !

**Comment by magefesa** [comment]
Any help possible ?

**Comment by xsteadfastx** [comment]
the report ends there where it gets interesting. ok but again... can you show your container configuration? what database you use? and can you run the a fresh container without any configuration?

**Comment by romu70** [comment]
Personaly I run Wallabag on my Syno without any issue (DS1513+). I run the @xsteadfastx image. But I run it from command line. Connect as root "sudo su -", and my command is:

```docker run --name wallabag -e "MYSQL_ROOT_PASSWORD=xxxxxx" -e "SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql" -e "SYMFONY__ENV__DATABASE_HOST=xxxxx" -e "SYMFONY__ENV__DATABASE_PORT=3306" -e "SYMFONY__ENV__DATABASE_NAME=wallabag" -e "SYMFONY__ENV__DATABASE_USER=wallabag" -e "SYMFONY__ENV__DATABASE_PASSWORD=xxxx" -d -p 4000:80 wallabag/wallabag```

Then, thanks to the DSM Application Portal (in the Control Panel), you can setup the reverse proxy to use your own domain to point to the http://localhost:4000 URL, and finally, with the Security applet, you can even ask for a Let's Encrypt certificate and....voilà!! Your own secure wallabag instance.

**Comment by magefesa** [comment]
Hi!!that s what i need !!!! Great ! Just one question :

Mysql pass is mariadb ? How can i install mysql??
Database host means ip of my syno right??

Thanks !! I know how to use web station to redirect the service to desired port !!!! 
Please answer my questions and i ll try as soon as possible!!

**Comment by magefesa** [comment]
The Docker is running !

1- Entering as root on terminal via SSH
2 - docker run --name wallabag-db -e "MYSQL_ROOT_PASSWORD=my_password" -d mariadb -p 4117:80 wallabag/wallabag
 All seems ok.... , but how can i access to wallabag ?? I ve used port 4117, and if i write this on chrome 👍 

http://local_nas_ip:4117

Nothing happens...any ideas ?? 
Please.... i m near !! sure !

**Comment by magefesa** [comment]
I m fighting  but no results... if i do this : docker run --name wallabag --link wallabag-db:wallabag-db -e "MYSQL_ROOT_PASSWORD=my_password -e "SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql" -e "SYMFONY__ENV__DATABASE_HOST=wallabag-db" -e "SYMFONY__ENV__DATABASE_PORT=3306" -e "SYMFONY__ENV__DATABASE_NAME=wallabag" -e "SYMFONY__ENV__DATABASE_USER=wallabag" -e "SYMFONY__ENV__DATABASE_PASSWORD=wallapass" -p **8117**:80 wallabag/wallabag

If i change 8117 by 80, the command runs, if i change the port, no.... any ideas please ?? I m finnished

**Comment by xsteadfastx** [comment]
do a `docker ps |grep wallabag` in the terminal please... this should output more info.

**Comment by xsteadfastx** [comment]
On Thu, 09. Feb 15:00, magefesa wrote:
> 1- Entering as root on terminal via SSH
> 2 - docker run --name wallabag-db -e "MYSQL_ROOT_PASSWORD=my_password" -d
> mariadb -p 4117:80 wallabag/wallabag
> All seems ok.... , but how can i access to wallabag ?? I ve used port 4117, and
> if i write this on chrome 👍

try this first `docker run --name wallabag -p 4117:80
wallabag/wallabag`. this starts a fresh container. i think something is
with your database.

**Comment by magefesa** [comment]
Same result  : 
[http://d.pr/i/PkvF]

But Wallabag is running, and port config is ok : 
[http://d.pr/i/4rLG](url)

I don t know what the hell is happening with original Wallabag Docker.... is really unbelievable

Thanks for your dedication, i m really disapponited, but since fiind a soluton, i ll use this version from another person : 
[http://d.pr/i/uvYy](url)

I would prefer 2.2, but... since then...

**Comment by romu70** [comment]
@magefesa, sorry for this late reply. Here are some answers:

- Yes, the MariaDB host is the syno address, on my nas, I installed the MariaDBpackage provided by Synology, not a separate container.
- MYSQL_ROOT_PASSWORD is the MariaDB root password.
- There is some work to be done to authorize your containers to access MariaDB, with such a command:
```GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.17.0.%' IDENTIFIED BY 'mariadb root password' WITH GRANT OPTION;```

To access your wallabag instance, open a browser on: http://your_nas_address:4117

Hope this helps.

**Comment by magefesa** [comment]
Please, can you help/explain to  me how to install without container on a Synology ?  I wanna try different approach, and probably installed on NAS web server will be faster. Actually i ve been trying on  a container (not official  docker), but is extremely slow

**Comment by xsteadfastx** [comment]
there is no output if you start a fresh wallabag container in the console?

**Comment by 3rain3ug** [comment]
Hi,
I think I've the same problem, but I could give more details for that.
Running the docker image with postgre db works until the first request.
He loads the favicon and a white blank page. In the Serverlog he shows me only one error for every request - it't an PHP Error telling that there is not enough random data to generate tokens ...

**Comment by 3rain3ug** [comment]
That was the error: 2017/04/01 12:29:30 [error] 192#192: *10 FastCGI sent in stderr: &quot;PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php:46
stdout
12:29:30

**Comment by 3rain3ug** [comment]
Maybe /dev/urandom is not readable?

**Comment by xsteadfastx** [comment]
On Sun, 02. Apr 03:39, 3rain3ug wrote:
> Hi,
> I think I've the same problem, but I could give more details for that.
> Running the docker image with postgre db works until the first request.
> He loads the favicon and a white blank page. In the Serverlog he shows me only
> one error for every request - it't an PHP Error telling that there is not
> enough random data to generate tokens ...

could you find out what kernel version your synalogy has?

**Comment by 3rain3ug** [comment]
uname -r
returns:
3.10.102

**Comment by xsteadfastx** [comment]
duplicate of #57
