### ISSUE TITLE
Isn't ansible overkill ?

### ISSUE THREAD

**Issue by billietl** [wallabag/docker#52]
Hi,

I wanted to use your docker image and I saw you used ansible to configure the container in the first run.
I love ansible and all, but embedding it in a container just for that is, IMHO, quite overkill since, form what I understand from it, it is only used to render templates and initialize databases.
This results in an image which is several 100s of MB large (this is huge when talking about docker).

Couldn't a couple of `sed`s and `if`s in a shell script do the work while making the image much tinier ?

**Comment by xsteadfastx** [comment]
i dont know. if you feel inspired to do everything with bash... we can talk about it. i think ansible is a nice and convenient way to do such tasks.... plus they are well tested. we have to deal with 3 kind of databases for example. handling all kind of environment variables. i dont think that its ansibles fault that the image is so large.

**Comment by tobru** [comment]
Ansible also get's in the way if you want to run this Wallabag image on OpenShift:

```
TASK [Gathering Facts] ********************************************************************************************************************************************************************************
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 402, in _execute
    self._play_context = self._play_context.set_task_and_variable_override(task=self._task, variables=variables, templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play_context.py", line 447, in set_task_and_variable_override
    new_info.remote_user = pwd.getpwuid(os.getuid()).pw_name
KeyError: 'getpwuid(): uid not found: 1000260000'

fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

The dynamic uid has no `/etc/passwd` entry and the solution described under [Support Arbitrary User IDs](https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html#openshift-container-platform-specific-guidelines) with using `nss_wrapper` is not that easy because Alpine does not really support this yet.

So considering to change to a simpler `bash` script would make this image much more compatible.

**Comment by xsteadfastx** [comment]
feel free to get started. i thought ansible is a convinient way of using a well tested database handling
