### ISSUE TITLE
Allow changing the database encoding

### ISSUE THREAD

**Issue by bnjbvr** [wallabag/docker#53]
Hi! See https://github.com/wallabag/wallabag/issues/2877 for context.

An article cannot be imported because the mysql encoding doesn't fit; I assume one needs to recreate the full database to change the encoding, so it might not be just a matter of changing the parameters at runtime, after all the containers have started.

Could we either allow changing the database encoding with an env variable, or set it to `utf8mb4` from the ground?

Cheers!

**Comment by xsteadfastx** [comment]
there are many questions for me... sure we can let ansible set the mysql encoding on start... but what happens if i change it? is it straight forward? im not a big mysql user myself.

**Comment by bnjbvr** [comment]
I think that once the DB is created, it can't change the type of the tables, unless they're destroyed? At least that's what I've seen (I had to recreate a Dockerfile with this change).

Note that the alternative would be to use an env variable for specifying the encoding, so that one can just use this instead, and set it to match whatever fits their needs.

**Comment by xsteadfastx** [comment]
i have no clue what to do. we have to test it what it exactly does.

**Comment by xsteadfastx** [comment]
Added it to #55
