### ISSUE TITLE
Composer running at container start phase

### ISSUE THREAD

**Issue by iMelnik** [wallabag/docker#6]
Hi,
You have composer running at start phase:
https://github.com/wallabag/docker/blob/master/root/etc/ansible/entrypoint.yml#L74
Is that totally necessary? 
I think you can remove this step to have a better start time

**Comment by xsteadfastx** [comment]
Right now its necessary to init the database. I wonder what it was. But
it didnt worked for me without this. Maybe we can test if its really
needed.

**Comment by nicosomb** [comment]
I close this old issue. If necessary, tell me if we need to reopen it.
