### ISSUE TITLE
Randomization unsufficient

### ISSUE THREAD

**Issue by theonlydoo** [wallabag/docker#61]
At first run, I'm having : 
```PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php```

maybe setup haveged ?

**Comment by tcitworld** [comment]
Duplicate of https://github.com/wallabag/docker/issues/57
