### ISSUE TITLE
External Access via NGINX 404

### ISSUE THREAD

**Issue by partymike** [wallabag/docker#68]
If I try to access the site externally I get this logged:

172.x.x.x - user [17/May/2017:13:34:32 +0000] "GET /wallabag HTTP/1.1" 404 300 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"

Which then gives a "The server returned a "404 Not Found" in chrome

If I access via the internal 192.168.10.60:8083 it works great

Line in NGINX:

	location ^~ /wallabag {
	include /config/nginx/proxy.conf;
	proxy_pass http://192.168.10.60:8083/;

-----
I use lots of other sites via nginx and they all work great using the above template.
wallabag works great, I have set it up in MYSQL...but while troubleshooting tried a simple 8083:80 config with no other variables and still had the same issue - which points at nginx.

Any ideas?

**Comment by partymike** [comment]
I have also tried adding a base path variable but no difference:

BASE_PATH=http://192.168.10.60:8083/wallabag

running on a synology

**Comment by xsteadfastx** [comment]
there are alot of bugs about running something on a synology. i dont have one and often cant reproduce this stuff on a normal linux box.

**Comment by partymike** [comment]
no worries sorted it :-)
