### ISSUE TITLE
Images saved inside container instead of linked volume

### ISSUE THREAD

**Issue by marblepebble** [wallabag/docker#71]
Using 2.2.3, I enabled the option to save the images on the pages as well as the pages themselves.
I found that the images are saved to /var/www/wallabag/web/assets/... rather than /var/www/wallabag/data/assets. Since the instructions only mention the data dir, this leaves the saved images in the non-persisted container, rather than the desired storage location.

**Comment by xsteadfastx** [comment]
ok thanks for the hint... im not a core developer so i didnt knew about this change.

could you tell me more about it @j0k3r @nicosomb?

**Comment by j0k3r** [comment]
Images are saved by default in `web/assets/images`.
Where did you get that instructions about the data folder?

**Comment by nicosomb** [comment]
I wonder if `data/assets` is not the path for wallabag v1.

**Comment by marblepebble** [comment]
@j0k3r The data folder is mentioned in the docker README "For persistent storage you should start the container with a volume:". Though I note on re-reading that this does appear to be specifically aimed at the users of SQLite.

This would seem to indicate that web/assets/images should be linked. Perhaps an update to the README to note this?

**Comment by j0k3r** [comment]
Oh yeah it's because the SQLite database is stored in the `data` folder.

@xsteadfastx could you update the readme to add this note about the folder `/var/www/wallabag/web/assets/images` that should be linked? (I don't know how to handle that using Docker)
