### ISSUE TITLE
TT-Rss to Wallabag v 2.x plugin

### ISSUE THREAD

**Issue by partymike** [wallabag/docker#72]
I wanted to install this plugin:
https://github.com/joshp23/ttrss-to-wallabag-v2

But it mentions installing CURL & copying to the plugins.local folder...

Is Curl installed in this docker? If so would I copy the above to plugins or plugins.local folder?

If Curl isn't installed is this easy to do?

Thanks for any help :-)

**Comment by nsteinmetz** [comment]
Hi,

Using ttrss on my side, (php5-)curl is required on the server on which you install ttrss but not wallabag.

The only thing you will do on wallabag side is creating a token so that ttrss can post urls to wallabag.

Hope it helps !

**Comment by xsteadfastx** [comment]
curl is installed but as @nsteinmetz says... i guess ttrss needs curl and not wallabag.
