### ISSUE TITLE
Does not honor "is_starred"

### ISSUE THREAD

**Issue by bobberb** [wallabag/docker#73]
On v2 import of fresh json export from 2.2.2, wallabag does not preserve stars.

Environment:
Docker image: latest (2.2.3)
DB: postgresql
Asynchronous: none
Import: json, v2
Errors: none reported from client
Host: arch x64, docker 1:17.05-01

**Comment by nicosomb** [comment]
Hello. 

This bug is not due to our docker image but due to wallabag. 
And it's fixed in the next minor release (2.3.0): https://github.com/wallabag/wallabag/pull/3143
