### ISSUE TITLE
 Found both group and host with same name

### ISSUE THREAD

**Issue by phineas0fog** [wallabag/docker#75]
Hello :)
When I try to launch wallabag with this command : `sudo docker run wallabag/wallabag`, its return this :    
    `Starting provisioner...
    [WARNING]: Found both group and host with same name: localhost`
...
So how to fix it ? :D
Thanks

**Comment by husimo** [comment]
I don't think it is really an issue. I had the same problem and thought it was stuck but several minutes after it worked (and now I have another problem).

**Comment by xsteadfastx** [comment]
It's just a warning

**Comment by Kopry** [comment]
Hello, I have the same problem,
But after
`Starting provisioner... [WARNING]: Found both group and host with same name: localhost`
I got a 
`Provisioner finished.`
And nothing

Any idea ? How to fix this ?

**Comment by RYNEQ** [comment]
> Hello, I have the same problem,
> But after
> `Starting provisioner... [WARNING]: Found both group and host with same name: localhost`
> I got a
> `Provisioner finished.`
> And nothing
> 
> Any idea ? How to fix this ?

same issue ! any solution?

**Comment by xardalph** [comment]
same here, fresh docker install on ubuntu 18.04, when i launch the container the cpu make spike to 100%.
when the "Provisionner finished" message appear the cpu go down, but nothing more
