### ISSUE TITLE
Docker image version

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/docker#76]
I didn't find any info about version of the current Docker image. For example, [with Redis](https://hub.docker.com/_/redis/) we have detailed tags denoting version, which is not the case of Wallabag. How can I found out the version I am pulling?
Wallabag page on DockerHub should be updated.

**Comment by xsteadfastx** [comment]
the wallabag docker image has tags for every wallabag version. or what do you mean?

**Comment by Suncatcher** [comment]
> the wallabag docker image has tags for every wallabag version
So how one could fetch them? Usually it's done via registry, but wallabag image [is absent in registry](https://registry.hub.docker.com/v1/repositories/wallabag/tags)

**Comment by Suncatcher** [comment]
It's commonly a good practice to place all tags onto a docker hub page

**Comment by xsteadfastx** [comment]
like this: https://hub.docker.com/r/wallabag/wallabag/tags/ ? 

you can pull them with `docker pull wallabag:2.2.1. like normal docker tags

**Comment by Suncatcher** [comment]
ok, thanks for hint:)

**Comment by nicosomb** [comment]
I close this issue. Feel free to reopen it if necessary.
