### ISSUE TITLE
Pocket consumer key

### ISSUE THREAD

**Issue by thomasschmit** [wallabag/docker#8]
When I add a `pocket_consumer_key` to `parameters.yml`, it mysteriously disappears when I restart the container. That's embarrassing. Can you have a look at it?

More info about the Pocket consumer key: http://doc.wallabag.org/en/master/user/import.html#from-pocket

**Comment by nicosomb** [comment]
Oups our documentation is old.
The consumer_key must be set in Settings screen of your wallabag.

Sent from my Alcatel Onetouch Idol 3 (4.7)
Le 4 mai 2016 17:45, Thomas Schmit <notifications@github.com> a écrit :When I add a pocket_consumer_key to parameters.yml, it mysteriously disappears when I restart the container. That's embarrassing. Can you have a look at it?

More info about the Pocket consumer key: http://doc.wallabag.org/en/master/user/import.html#from-pocket

**Comment by thomasschmit** [comment]
Thanks for your help!
