### ISSUE TITLE
Migration error after updating 2.2 to 2.3

### ISSUE THREAD

**Issue by Yamakuni** [wallabag/docker#91]
I upgraded to 2.3 and tried to migrate, but I have this error

                     Application Migrations

    Migrating up to 20171125164500 from 0

     ++ migrating 20160401000000

     -> CREATE TABLE wallabag_craue_config_setting (name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, section VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name));
    Migration 20160401000000 failed during Execution. Error An exception occurred while executing 'CREATE TABLE wallabag_craue_config_setting (name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, section VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name));':

    SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists
    07:53:44 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --env=prod --no-interaction". Message: "An exception occurred while executing 'CREATE TABLE wallabag_craue_config_setting (name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, section VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name));':

     SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists" ["error" => Doctrine\DBAL\Exception\TableExistsException { …},"command" => "doctrine:migrations:migrate --env=prod --no-interaction","message" => """  An exception occurred while executing 'CREATE TABLE wallabag_craue_config_setting (name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, section VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name));':\n  \n  SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists  """] []

       [Doctrine\DBAL\Exception\TableExistsException]
       An exception occurred while executing 'CREATE TABLE wallabag_craue_config_setting (name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, section VARCHAR(255) DEFAULT NUL
       L, PRIMARY KEY(name));':

       SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists

       [Doctrine\DBAL\Driver\PDOException]
       SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists

       [PDOException]
       SQLSTATE[HY000]: General error: 1 table wallabag_craue_config_setting already exists

     doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

Any idea?

**Comment by nicosomb** [comment]
Hello @Yamakuni. 

Thank you for reporting this bug. 
Could you run these queries: https://github.com/wallabag/wallabag/issues/3480#issuecomment-350975801 in your database container?

**Comment by Yamakuni** [comment]
Hey @nicosomb 
Thanks for your help!

I haven't database container.
I lauched Wallabag docker with this command : 

    $ docker run -v /opt/wallabag/data:/var/www/wallabag/data  -p 80:80 wallabag/wallabag 

I seen this : [wallabag/wallabag#3480 (comment) ](https://github.com/wallabag/wallabag/issues/3480#issuecomment-350975801), but I don't undestand what I have to do.

**Comment by aaa2000** [comment]
Maybe try:

```
docker exec -t NAME_OR_ID_OF_YOUR_WALLABAG_CONTAINER /var/www/wallabag/bin/console doctrine:query:sql --env=prod --no-interaction "INSERT INTO ..."
```

Change the `INSERT INTO` by the query in https://github.com/wallabag/wallabag/issues/3480#issuecomment-350975801

**Comment by aaa2000** [comment]
Or maybe more simple

```
docker exec -t NAME_OR_ID_OF_YOUR_WALLABAG_CONTAINER /var/www/wallabag/bin/console  bin/console doctrine:migrations:version --add --range-from=20160401000000 --range-to=20170127093841
```

**Comment by Yamakuni** [comment]
Thanks @aaa2000 for your help!

I tried, and got errors for both!

**1st idea** - command :

     docker exec -t wallabag /var/www/wallabag/bin/console doctrine:query:sql --env=prod --no-interaction "INSERT INTO `migration_versions` (`version`)"

I got this error : 

    zsh: command not found: migration_versions
    zsh: command not found: version
    09:11:38 ERROR     [console] Error thrown while running command "doctrine:query:sql --env=prod --no-interaction 'INSERT INTO  ()'". Message: "An exception occurred while executing 'INSERT INTO  ()':

    SQLSTATE[HY000]: General error: 1 near "(": syntax error" ["error" => Doctrine\DBAL\Exception\SyntaxErrorException { …},"command" => "doctrine:query:sql --env=prod --no-interaction 'INSERT INTO  ()'","message" => """  An exception occurred while executing 'INSERT INTO  ()':\n  \n  SQLSTATE[HY000]: General error: 1 near "(": syntax error  """] []


       [Doctrine\DBAL\Exception\SyntaxErrorException]
      An exception occurred while executing 'INSERT INTO  ()':

      SQLSTATE[HY000]: General error: 1 near "(": syntax error



    [Doctrine\DBAL\Driver\PDOException]
    SQLSTATE[HY000]: General error: 1 near "(": syntax error



     [PDOException]
     SQLSTATE[HY000]: General error: 1 near "(": syntax error


    doctrine:query:sql [--depth DEPTH] [--connection [CONNECTION]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <sql>

-------------------------

**2nd idea** -  command :

    docker exec -t wallabag /var/www/wallabag/bin/console  bin/console doctrine:migrations:version --add --range-from=20160401000000 --range-to=20170127093841

I got this error 

    PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
    Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:49
    Stack trace:
    #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
    #1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
    #2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(59): Symfony\Component\HttpKernel\Kernel->boot()
    #3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #4 /var/www/wallabag/bin/console(29): Symfony\Component\Console in /var/www/wallabag/app/AppKernel.php on line 49

**Comment by aaa2000** [comment]
The second command seems to work only in development environment. The query of the first command is incomplete, try this

```
docker exec -t wallabag /var/www/wallabag/bin/console doctrine:query:sql --env=prod --no-interaction "INSERT INTO `migration_versions` (`version`) VALUES ('20160401000000'), ('20160410190541'), ('20160812120952'), ('20160911214952'), ('20160916201049'), ('20161001072726'), ('20161022134138'), ('20161024212538'), ('20161031132655'), ('20161104073720'), ('20161106113822'), ('20161117071626'), ('20161118134328'), ('20161122144743'), ('20161122203647'), ('20161128084725'), ('20161128131503'), ('20161214094402'), ('20161214094403'), ('20170127093841');"
```

**Comment by Yamakuni** [comment]
@aaa2000 
Thanks for your answer.

I tried and got this error : 

    zsh: command not found: migration_versions
    zsh: command not found: version
    [sudo] password for pi:
    09:38:12 ERROR     [console] Error thrown while running command "doctrine:query:sql --env=prod --no-interaction 'INSERT INTO  () VALUES ('\''20160401000000'\''), ('\''20160410190541'\''), ('\''20160812120952'\''), ('\''20160911214952'\''), ('\''20160916201049'\''), ('\''20161001072726'\''), ('\''20161022134138'\''), ('\''20161024212538'\''), ('\''20161031132655'\''), ('\''20161104073720'\''), ('\''20161106113822'\''), ('\''20161117071626'\''), ('\''20161118134328'\''), ('\''20161122144743'\''), ('\''20161122203647'\''), ('\''20161128084725'\''), ('\''20161128131503'\''), ('\''20161214094402'\''), ('\''20161214094403'\''), ('\''20170127093841'\'');'". Message: "An exception occurred while executing 'INSERT INTO  () VALUES ('20160401000000'), ('20160410190541'), ('20160812120952'), ('20160911214952'), ('20160916201049'), ('20161001072726'), ('20161022134138'), ('20161024212538'), ('20161031132655'), ('20161104073720'), ('20161106113822'), ('20161117071626'), ('20161118134328'), ('20161122144743'), ('20161122203647'), ('20161128084725'), ('20161128131503'), ('20161214094402'), ('20161214094403'), ('20170127093841');':

    SQLSTATE[HY000]: General error: 1 near "(": syntax error" ["error" => Doctrine\DBAL\Exception\SyntaxErrorException { …},"command" => "doctrine:query:sql --env=prod --no-interaction 'INSERT INTO  () VALUES ('\''20160401000000'\''), ('\''20160410190541'\''), ('\''20160812120952'\''), ('\''20160911214952'\''), ('\''20160916201049'\''), ('\''20161001072726'\''), ('\''20161022134138'\''), ('\''20161024212538'\''), ('\''20161031132655'\''), ('\''20161104073720'\''), ('\''20161106113822'\''), ('\''20161117071626'\''), ('\''20161118134328'\''), ('\''20161122144743'\''), ('\''20161122203647'\''), ('\''20161128084725'\''), ('\''20161128131503'\''), ('\''20161214094402'\''), ('\''20161214094403'\''), ('\''20170127093841'\'');'","message" => """  An exception occurred while executing 'INSERT INTO  () VALUES ('20160401000000'), ('20160410190541'), ('20160812120952'), ('20160911214952'), ('20160916201049'), ('20161001072726'), ('20161022134138'), ('20161024212538'), ('20161031132655'), ('20161104073720'), ('20161106113822'), ('20161117071626'), ('20161118134328'), ('20161122144743'), ('20161122203647'), ('20161128084725'), ('20161128131503'), ('20161214094402'), ('20161214094403'), ('20170127093841');':\n  \n  SQLSTATE[HY000]: General error: 1 near "(": syntax error  """] []


    [Doctrine\DBAL\Exception\SyntaxErrorException]
    An exception occurred while executing 'INSERT INTO  () VALUES ('20160401000000'), ('20160410190541'), ('20160812120952'), ('20160911214952'), ('20160916201049'), ('20161001072726'), ('20161022134138'), ('20161024212538'), ('20161031132655'), ('20161104073720'), ('20161106113822'), ('20161117071626'), ('20161118134328'), ('20161122144743'), ('20161122203647'), ('20161128084725'), ('20161128131503'), ('20161214094402'), ('20161214094403'), ('20170127093841');':

    SQLSTATE[HY000]: General error: 1 near "(": syntax error



    [Doctrine\DBAL\Driver\PDOException]
    SQLSTATE[HY000]: General error: 1 near "(": syntax error



    [PDOException]
    SQLSTATE[HY000]: General error: 1 near "(": syntax error


    doctrine:query:sql [--depth DEPTH] [--connection [CONNECTION]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <sql>

**Comment by aaa2000** [comment]
I have updated later my comment  to remove the backtick, it seems you have running the command with backtick because the table name and column name are empty

**Comment by Yamakuni** [comment]
It works!
Thanks  @aaa2000 

I did : 

    docker exec -t NAME_OR_ID_OF_YOUR_WALLABAG_CONTAINER /var/www/wallabag/bin/console doctrine:query:sql --env=prod --no-interaction "INSERT INTO migration_versions (version) VALUES ('20160401000000'), ('20160410190541'), ('20160812120952'), ('20160911214952'), ('20160916201049'), ('20161001072726'), ('20161022134138'), ('20161024212538'), ('20161031132655'), ('20161104073720'), ('20161106113822'), ('20161117071626'), ('20161118134328'), ('20161122144743'), ('20161122203647'), ('20161128084725'), ('20161128131503'), ('20161214094402'), ('20161214094403'), ('20170127093841');"

Then I tried the migration again : 

    docker exec -t NAME_OR_ID_OF_YOUR_WALLABAG_CONTAINER /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction

I've had a lot of errors, but it works, and everything looks fine.

Thank you for your help!
